"""Frozen Wave 7 Central/East pass-2 identity and row-review data."""

from __future__ import annotations

from typing import Any


def _source(
    source_id: str,
    publisher: str,
    title: str,
    url: str,
) -> dict[str, Any]:
    return {
        "id": source_id,
        "title": title,
        "url": url,
        "publisher": publisher,
        "license": "Citation and link only",
        "source_type": "official_or_academic_reference",
        "accessed": "2026-07-16",
        "source_family_id": f"wave7_central_pass2_{source_id}",
        "evidence_roles": ["identity_boundary_or_context_reference"],
    }


WAVE7_CENTRAL_PASS2_SOURCES = [
    _source(
        "wave7_p2_sardinia_identity_cambridge",
        "Cambridge University Press",
        "Piedmont and the Kingdom of Sardinia before Italian unification",
        "https://www.cambridge.org/core/books/paying-for-the-liberal-state/always-on-the-brink-piedmont-and-italy/876F1CA4FD215A387C8474C7661CBDFF",
    ),
    _source(
        "wave7_p2_sardinia_campaigns_army",
        "Italian Army",
        "Kingdom of Sardinia campaign and battle history, 1848-1859",
        "https://www.esercito.difesa.it/en/organization/the-chief-of-general-staff-of-the-army/comfoter/northern-operational-forces-command/pozzuolo%20del%20friuli-cavalry-brigade/history/123602.html",
    ),
    _source(
        "wave7_p2_castelfidardo_army",
        "Italian Army",
        "Castelfidardo and Ancona campaign history",
        "https://www.esercito.difesa.it/comunicazione/editoria/Rivista-Militare/archivio/Documents/2007/Rivista%20Militare%202007%20-%20Numero%203.pdf",
    ),
    _source(
        "wave7_p2_gaeta_cambridge",
        "Cambridge University Press",
        "The siege of Gaeta, November 1860-February 1861",
        "https://www.cambridge.org/core/books/civil-war-and-agrarian-unrest/introduction/3B039798686E1BE66EFAA93FDA643BFE",
    ),
    _source(
        "wave7_p2_savra_elsie",
        "Robert Elsie Albanian History Archive",
        "Balsha II and the Battle of Savra in 1385",
        "https://www.albanianhistory.net/1956_Vlora/index.html",
    ),
    _source(
        "wave7_p2_lezhe_albania_mod",
        "Ministry of Defence of Albania",
        "League of Lezhe and Skanderbeg battle chronology",
        "https://www.mod.gov.al/images/gazetaushtria/pdf/2023/mars/ushtria_3_3_2023.pdf",
    ),
    _source(
        "wave7_p2_abushiri_cambridge",
        "Cambridge University Press",
        "Abushiri revolt in German East Africa, 1888-1890",
        "https://www.cambridge.org/core/journals/british-journal-of-political-science/article/territorial-expansion-of-the-colonial-state-evidence-from-german-east-africa-18901909/709EEF58BC4BD8A27B5856B663EB7F59",
    ),
    _source(
        "wave7_p2_arab_revolt_nam",
        "National Army Museum",
        "Hashemite Arab forces, Aqaba, and Tafileh in the Arab Revolt",
        "https://www.nam.ac.uk/explore/lawrence-arabia-man-behind-robes",
    ),
    _source(
        "wave7_p2_arab_revolt_army",
        "US Army University Press",
        "Evolution of a Revolt: Arab forces and the Medina campaign",
        "https://www.armyupress.army.mil/Portals/7/combat-studies-institute/csi-books/evolution-of-a-revolt.pdf",
    ),
    _source(
        "wave7_p2_samnium_cambridge",
        "Cambridge University Press",
        "Samnium as a confederacy of independent tribes",
        "https://www.cambridge.org/core/books/history-of-rome/first-samnite-war/3B2CCFF5B504A9FC34B12E254ACC9561",
    ),
    _source(
        "wave7_p2_caudine_cambridge",
        "Cambridge University Press",
        "The Samnite victory and Roman surrender at the Caudine Forks",
        "https://www.cambridge.org/core/journals/journal-of-roman-studies/article/abs/pax-caudina/88BA1B5572D3B4D67C4256F2A3A2CCA4",
    ),
    _source(
        "wave7_p2_sentinum_livy",
        "Perseus Digital Library, Tufts University",
        "Livy on the Samnite and Gallic coalition at Sentinum",
        "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0026%3Abook%3D10%3Achapter%3D27",
    ),
    _source(
        "wave7_p2_sentinum_cambridge",
        "Cambridge University Press",
        "Coalition belligerents before Sentinum",
        "https://assets.cambridge.org/97805215/16945/excerpt/9780521516945_excerpt.pdf",
    ),
    _source(
        "wave7_p2_lautulae_diodorus",
        "University of Chicago LacusCurtius",
        "Ancient traditions disagreeing over the result at Lautulae",
        "https://penelope.uchicago.edu/thayer/e/roman/texts/diodorus_siculus/19d%2A.html",
    ),
    _source(
        "wave7_p2_social_war_appian",
        "University of Chicago LacusCurtius",
        "Appian on the distinct Samnite and Marsic actors in the Social War",
        "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Appian/Civil_Wars/1%2A.html",
    ),
    _source(
        "wave7_p2_samnite_chronology_attalus",
        "Attalus historical source index",
        "Ancient-source chronology for Samnium and Rome",
        "https://www.attalus.org/names/s/samnium.html",
    ),
]


def _entity(
    entity_id: str,
    name: str,
    kind: str,
    start_year: int,
    end_year: int,
    region: str,
    source_ids: tuple[str, ...],
) -> dict[str, Any]:
    return {
        "id": entity_id,
        "name": name,
        "kind": kind,
        "start_year": start_year,
        "end_year": end_year,
        "region": region,
        "aliases": [],
        "predecessors": [],
        "continuity_note": (
            "Exact Wave 7 Central/East pass-2 reviewed-party boundary. It opens "
            "no broad alias, country-label, or cross-era fallback, and no "
            "predecessor or successor rating is inherited."
        ),
        "source_ids": list(source_ids),
    }


WAVE7_CENTRAL_PASS2_ENTITIES = [
    _entity(
        "kingdom_sardinia_piedmont",
        "Kingdom of Sardinia (Piedmont)",
        "kingdom",
        1720,
        1861,
        "Southern Europe",
        ("wave7_p2_sardinia_identity_cambridge",),
    ),
    _entity(
        "balsa_ii_forces_savra_1385",
        "Forces of Balsha II at Savra",
        "dynastic_forces",
        1385,
        1385,
        "Southeastern Europe",
        ("wave7_p2_savra_elsie",),
    ),
    _entity(
        "league_lezhe_forces",
        "League of Lezhe Forces",
        "military_league",
        1444,
        1468,
        "Southeastern Europe",
        ("wave7_p2_lezhe_albania_mod",),
    ),
    _entity(
        "abushiri_revolt_forces",
        "Abushiri Revolt Forces",
        "rebel_forces",
        1888,
        1890,
        "East Africa",
        ("wave7_p2_abushiri_cambridge",),
    ),
    _entity(
        "hashemite_arab_revolt_forces",
        "Hashemite Arab Revolt Forces",
        "rebel_forces",
        1916,
        1919,
        "Arabian Peninsula",
        ("wave7_p2_arab_revolt_nam", "wave7_p2_arab_revolt_army"),
    ),
    _entity(
        "samnite_confederation_wars",
        "Samnite Confederation of the Samnite Wars",
        "tribal_confederation",
        -343,
        -290,
        "Italian Peninsula",
        ("wave7_p2_samnium_cambridge",),
    ),
    _entity(
        "samnite_social_war_insurgents",
        "Samnite Insurgents of the Social War",
        "insurgent_forces",
        -91,
        -88,
        "Italian Peninsula",
        ("wave7_p2_social_war_appian",),
    ),
]


def _review(
    candidate_id: str,
    raw_row_sha256: str,
    source_row: int,
    name: str,
    year_low: int,
    year_high: int,
    side_1_raw: str,
    side_2_raw: str,
    winner_raw: str,
    loser_raw: str | None,
) -> dict[str, Any]:
    return {
        "candidate_id": candidate_id,
        "raw_row_sha256": raw_row_sha256,
        "raw_contract": {
            "candidate_id": candidate_id,
            "source_row": source_row,
            "name": name,
            "year_low": year_low,
            "year_high": year_high,
            "side_1_raw": side_1_raw,
            "side_2_raw": side_2_raw,
            "winner_raw": winner_raw,
            "loser_raw": loser_raw,
        },
    }


def _promotion(
    row: tuple[Any, ...],
    side_1_entity_ids: tuple[str, ...],
    side_2_entity_ids: tuple[str, ...],
    cohort: str,
    evidence_refs: tuple[str, ...],
    audit_note: str,
) -> dict[str, Any]:
    reviewed = _review(*row)
    raw = reviewed["raw_contract"]
    winner_raw = raw["winner_raw"]
    if winner_raw == "Draw":
        result = {"type": "draw"}
    elif winner_raw == raw["side_1_raw"]:
        result = {"type": "win", "winner_side": 1}
    elif winner_raw == raw["side_2_raw"]:
        result = {"type": "win", "winner_side": 2}
    else:
        raise ValueError(f"Unaligned frozen result for {reviewed['candidate_id']}")
    reviewed.update(
        {
            "side_1_entity_ids": side_1_entity_ids,
            "side_2_entity_ids": side_2_entity_ids,
            "result": result,
            "cohort": cohort,
            "evidence_refs": evidence_refs,
            "audit_note": audit_note,
            "canonical_event": {
                "name": raw["name"],
                "year_low": raw["year_low"],
                "year_high": raw["year_high"],
                "date_precision": "year",
                "granularity": "engagement",
                "canonical_key": f"wave7-central-pass2:{reviewed['candidate_id']}",
            },
        }
    )
    return reviewed


def _hold(
    row: tuple[Any, ...],
    cohort: str,
    category: str,
    latent: bool,
    evidence_refs: tuple[str, ...],
    reason: str,
) -> dict[str, Any]:
    reviewed = _review(*row)
    reviewed.update(
        {
            "cohort": cohort,
            "category": category,
            "latent": latent,
            "evidence_refs": evidence_refs,
            "reason": reason,
        }
    )
    return reviewed


_PIEDMONT = ("kingdom_sardinia_piedmont",)
_BALSHA = ("balsa_ii_forces_savra_1385",)
_LEZHE = ("league_lezhe_forces",)
_ABUSHIRI = ("abushiri_revolt_forces",)
_ARAB_REVOLT = ("hashemite_arab_revolt_forces",)
_SAMNITE_WARS = ("samnite_confederation_wars",)
_SAMNITE_SOCIAL = ("samnite_social_war_insurgents",)
_SARDINIA_EVIDENCE = (
    "wave7_p2_sardinia_identity_cambridge",
    "wave7_p2_sardinia_campaigns_army",
)
_LEZHE_EVIDENCE = ("wave7_p2_lezhe_albania_mod",)
_ARAB_EVIDENCE = ("wave7_p2_arab_revolt_nam", "wave7_p2_arab_revolt_army")
_SAMNITE_EVIDENCE = (
    "wave7_p2_samnium_cambridge",
    "wave7_p2_samnite_chronology_attalus",
)


WAVE7_CENTRAL_PASS2_PROMOTION_CONTRACTS = {
    row["candidate_id"]: row
    for row in [
        _promotion(
            (
                "hced-Mount Gaurus-342-1",
                "ebb84fe7ead10c64751ac05f920190b74a604e3d34b8c0f702c45a0eea723047",
                10863,
                "Mount Gaurus",
                -342,
                -342,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            ("roman_republic",),
            _SAMNITE_WARS,
            "samnite_wars",
            _SAMNITE_EVIDENCE,
            "The ancient label is confined to the Samnite confederation of the Samnite Wars.",
        ),
        _promotion(
            (
                "hced-Caudine Forks-321-1",
                "8dae2a99f13bfb1396105a048264c712a70e6a14ae13b0d3b5d13e857bda2668",
                3345,
                "Caudine Forks",
                -321,
                -321,
                "Samnites",
                "Rome",
                "Samnites",
                "Rome",
            ),
            _SAMNITE_WARS,
            ("roman_republic",),
            "samnite_wars",
            ("wave7_p2_samnium_cambridge", "wave7_p2_caudine_cambridge"),
            "The Caudine surrender is bound to the ancient Samnite confederation, not later Social War insurgents.",
        ),
        _promotion(
            (
                "hced-Tarracina-314-1",
                "247e1f21abeb2460f7addaaf92da25fd2bee2661cd58d3f69f9c12cb38816075",
                15661,
                "Tarracina",
                -314,
                -314,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            ("roman_republic",),
            _SAMNITE_WARS,
            "samnite_wars",
            _SAMNITE_EVIDENCE,
            "The ancient label is confined to the Samnite confederation of the Samnite Wars.",
        ),
        _promotion(
            (
                "hced-Bovianum-305-1",
                "05a10ba10ddb6048c960b0c3d658f323928de4aa63814e6ce2a998d3d93c3796",
                2487,
                "Bovianum",
                -305,
                -305,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            ("roman_republic",),
            _SAMNITE_WARS,
            "samnite_wars",
            _SAMNITE_EVIDENCE,
            "The ancient label is confined to the Samnite confederation of the Samnite Wars.",
        ),
        _promotion(
            (
                "hced-Aquilonia-293-1",
                "cc253a8f1ede91e4fd02b8dd871d4d028b5c6e23c4cbdef75648eeef414fc4b8",
                955,
                "Aquilonia",
                -293,
                -293,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            ("roman_republic",),
            _SAMNITE_WARS,
            "samnite_wars",
            _SAMNITE_EVIDENCE,
            "The ancient label is confined to the Samnite confederation of the Samnite Wars.",
        ),
        _promotion(
            (
                "hced-Acerrae-90-1",
                "f5a7fac374403cd2eafb08623d6098a956ead196b4f215ec17504080d85a9b27",
                75,
                "Acerrae",
                -90,
                -90,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            ("roman_republic",),
            _SAMNITE_SOCIAL,
            "samnite_social_war",
            ("wave7_p2_social_war_appian",),
            "The row is bound to distinct Samnite Social War insurgents, not the ancient confederation.",
        ),
        _promotion(
            (
                "hced-Savra1385-1",
                "894cb23215ef3011c439e259f9c19d300d1bbe4848c88da0fa1246e862d1b040",
                14397,
                "Savra",
                1385,
                1385,
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
                "Albania",
            ),
            ("ottoman_empire",),
            _BALSHA,
            "albania_savra",
            ("wave7_p2_savra_elsie",),
            "The broad Albania label is narrowed to the forces of Balsha II at Savra.",
        ),
        _promotion(
            (
                "hced-Domosdova1444-1",
                "b464ad5513f48fe0d18e28c6beb396aa8eafebcb32c5c361a6b8642e14c21fd9",
                4833,
                "Domosdova",
                1444,
                1444,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            _LEZHE,
            ("ottoman_empire",),
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The Albania label is confined to League of Lezhe forces in Skanderbeg's campaign.",
        ),
        _promotion(
            (
                "hced-Dibra1448-1",
                "4a9b122b1503cf008829d720100575a44cf2dd013c4224c86f23e0b86f149672",
                4721,
                "Dibra",
                1448,
                1448,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            _LEZHE,
            ("ottoman_empire",),
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The Albania label is confined to League of Lezhe forces in Skanderbeg's campaign.",
        ),
        _promotion(
            (
                "hced-Svetigrad1448-1",
                "7b0a18325fa463dd854cde60342e02f368e6d419fe3584bfc9916bf2db4a6b36",
                15397,
                "Svetigrad",
                1448,
                1448,
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
                "Albania",
            ),
            ("ottoman_empire",),
            _LEZHE,
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The Albania label is confined to League of Lezhe forces in Skanderbeg's campaign.",
        ),
        _promotion(
            (
                "hced-Kruje, Albania1450-1",
                "742a2d928c81e4c2ea0445f76c6594b873698c4265fefa43a6e2c890d6ff76bb",
                8643,
                "Kruje, Albania",
                1450,
                1450,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            _LEZHE,
            ("ottoman_empire",),
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The 1450 Kruje row matches the documented League of Lezhe defense.",
        ),
        _promotion(
            (
                "hced-Oranik1456-1",
                "017aed135b6e022090f8bbf23d210885b18ce5d0edded2f9a7987277e6be107f",
                11853,
                "Oranik",
                1456,
                1456,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            _LEZHE,
            ("ottoman_empire",),
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The Albania label is confined to League of Lezhe forces in Skanderbeg's campaign.",
        ),
        _promotion(
            (
                "hced-Albulen1457-1",
                "68e081be44981447486536f37193f9c2df809bbc7811034a5777365a810bf39c",
                377,
                "Albulen",
                1457,
                1457,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            _LEZHE,
            ("ottoman_empire",),
            "albania_lezhe",
            _LEZHE_EVIDENCE,
            "The Albania label is confined to League of Lezhe forces in Skanderbeg's campaign.",
        ),
        _promotion(
            (
                "hced-Mondovi1796-1",
                "ef2b474c4e626096ea11be953bac8ab00b53178d388b9b510012e15adc85414d",
                10629,
                "Mondovi",
                1796,
                1796,
                "France",
                "Piedmont",
                "France",
                "Piedmont",
            ),
            ("french_first_republic",),
            _PIEDMONT,
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont denotes the Kingdom of Sardinia's armed forces, not a successor Italian rating.",
        ),
        _promotion(
            (
                "hced-Custozza1848-1",
                "bc4fbe929861b90bd9f7e86b010142e6d17d01bc3b2481d8f0e9c97c7b89bcb2",
                4349,
                "Custozza",
                1848,
                1848,
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
            ),
            ("austrian_empire",),
            _PIEDMONT,
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Goito1848-1",
                "e0dbd3b95dbb078519404e5e33170c42073b360dc71b7f34246702560c4991ae",
                6265,
                "Goito",
                1848,
                1848,
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
            ),
            _PIEDMONT,
            ("austrian_empire",),
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Pastrengo1848-1",
                "e47d11ed2ccfbe42c896ce4a21bfc7a5007868f90bfce9eea63817647a76b622",
                12237,
                "Pastrengo",
                1848,
                1848,
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
            ),
            _PIEDMONT,
            ("austrian_empire",),
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Santa Lucia1848-1",
                "28f44b4ea0e3b1006eb7edb9423f9b602f294319f970c191b062ddd6df829b21",
                14205,
                "Santa Lucia",
                1848,
                1848,
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
            ),
            ("austrian_empire",),
            _PIEDMONT,
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Mortara1849-1",
                "b6c34a07fe0e3eaf59d8376be2dfbf4cc2ae2aee3a0d96cdb3a88082d0854085",
                10813,
                "Mortara",
                1849,
                1849,
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
            ),
            ("austrian_empire",),
            _PIEDMONT,
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Novara1849-1",
                "cb1e4324e2bf69771730e7c4cb15c0c5654bf02265297c26259316a7d7b27bfe",
                11621,
                "Novara",
                1849,
                1849,
                "Habsburg Empire",
                "Piedmont",
                "Habsburg Empire",
                "Piedmont",
            ),
            ("austrian_empire",),
            _PIEDMONT,
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont is resolved as the Kingdom of Sardinia and Habsburg Empire as the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Palestro1859-1",
                "c261c9d2558d27c27cc7a9eaa6aa6a2fa4334edd90114d3c9e40335e8a9ec7fc",
                12069,
                "Palestro",
                1859,
                1859,
                "Piedmont",
                "Austria",
                "Piedmont",
                "Austria",
            ),
            _PIEDMONT,
            ("austrian_empire",),
            "piedmont_sardinia",
            _SARDINIA_EVIDENCE,
            "Piedmont denotes the Kingdom of Sardinia; Austria remains the Austrian Empire.",
        ),
        _promotion(
            (
                "hced-Ancona1860-1",
                "215e5879ae3bff29507dbc151e3a5d204e1fef1fc0c994ea424ab7a360bb91a2",
                783,
                "Ancona",
                1860,
                1860,
                "Piedmont",
                "Papal States",
                "Piedmont",
                "Papal States",
            ),
            _PIEDMONT,
            ("clio_it_papal_state_1_755_50394c66",),
            "piedmont_sardinia",
            ("wave7_p2_sardinia_identity_cambridge", "wave7_p2_castelfidardo_army"),
            "The 1860 Piedmont label remains the Kingdom of Sardinia; the Papal opponent stays explicit.",
        ),
        _promotion(
            (
                "hced-Castelfidardo1860-1",
                "8fc0c3ad29cbe5c318f04428a7299ad0748e0ccaaeb75d76612615673f01daa0",
                3285,
                "Castelfidardo",
                1860,
                1860,
                "Piedmont",
                "Papal States",
                "Piedmont",
                "Papal States",
            ),
            _PIEDMONT,
            ("clio_it_papal_state_1_755_50394c66",),
            "piedmont_sardinia",
            ("wave7_p2_sardinia_identity_cambridge", "wave7_p2_castelfidardo_army"),
            "The 1860 Piedmont label remains the Kingdom of Sardinia; the Papal opponent stays explicit.",
        ),
        _promotion(
            (
                "hced-Pangani1889-1",
                "22fa6a4d600b98a3945cf9ea4e359a6a746d302a695f3f25726384d5fa8572a5",
                12135,
                "Pangani",
                1889,
                1889,
                "Germany",
                "Arab Rebels",
                "Germany",
                "Arab Rebels",
            ),
            ("german_empire",),
            _ABUSHIRI,
            "abushiri_revolt",
            ("wave7_p2_abushiri_cambridge",),
            "The East African Arab Rebels label denotes Abushiri revolt forces, not the later Arab Revolt.",
        ),
        _promotion(
            (
                "hced-Hejaz1916-1",
                "efebd97cd461c20690261669332667852bb925868bdd9c1bbe0ac781b63dbdf9",
                6897,
                "Hejaz",
                1916,
                1916,
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "The label is confined to Hashemite Arab Revolt forces in 1916-1919.",
        ),
        _promotion(
            (
                "hced-Medina, Saudi Arabia1916-1919-1",
                "6fa6a25b66edb078ce51543920a5e201b6731a03af124684eec53750d3270613",
                10223,
                "Medina, Saudi Arabia",
                1916,
                1919,
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
            ),
            ("ottoman_empire",),
            _ARAB_REVOLT,
            "hashemite_arab_revolt",
            ("wave7_p2_arab_revolt_army",),
            "The multi-year Medina row records the Ottoman tactical defense against Hashemite revolt forces, not the war's strategic result.",
        ),
        _promotion(
            (
                "hced-Taif1916-1",
                "6197425e6e31f29a1123b5b035437245c1d75ea43d34587e6ad062e6955dd9c4",
                15511,
                "Taif",
                1916,
                1916,
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "The label is confined to Hashemite Arab Revolt forces in 1916-1919.",
        ),
        _promotion(
            (
                "hced-Yanbu (1st)1916-1",
                "9f62860278f69194fadba50776b17467d23d68dca0fc091363bfd8cf5c94a1ed",
                17469,
                "Yanbu (1st)",
                1916,
                1916,
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "The label is confined to Hashemite Arab Revolt forces in 1916-1919.",
        ),
        _promotion(
            (
                "hced-Aqaba1917-1",
                "68cc89a63ca861d01c86a0d518ae283bba1ed8333e9d8292bb290997456da47d",
                933,
                "Aqaba",
                1917,
                1917,
                "Arab Rebels",
                "Turkey",
                "Arab Rebels",
                "Turkey",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "Turkey is normalized to the Ottoman Empire inside the documented Arab Revolt window.",
        ),
        _promotion(
            (
                "hced-Wejh1917-1",
                "8b41684cdcbc82829032341507e7cbc4ca62a8712b9f967db27f719a1357fcb3",
                17183,
                "Wejh",
                1917,
                1917,
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "The label is confined to Hashemite Arab Revolt forces in 1916-1919.",
        ),
        _promotion(
            (
                "hced-Tafileh1918-1",
                "b9ad81a7b9343b96fdce049e20ee702b154fd949c001238590ea3eabd5305c47",
                15491,
                "Tafileh",
                1918,
                1918,
                "Arab Rebels",
                "Ottoman Empire",
                "Arab Rebels",
                "Ottoman Empire",
            ),
            _ARAB_REVOLT,
            ("ottoman_empire",),
            "hashemite_arab_revolt",
            _ARAB_EVIDENCE,
            "The label is confined to Hashemite Arab Revolt forces in 1916-1919.",
        ),
    ]
}


WAVE7_CENTRAL_PASS2_HOLDS = {
    row["candidate_id"]: row
    for row in [
        _hold(
            (
                "hced-Lautulae-315-1",
                "dd8c77b25fd4dc240fb5e2a1135db68ba31113198843e86c650dacae3454c870",
                9051,
                "Lautulae",
                -315,
                -315,
                "Samnites",
                "Rome",
                "Samnites",
                "Rome",
            ),
            "samnite_wars",
            "disputed_outcome",
            True,
            ("wave7_p2_lautulae_diodorus", "wave7_p2_samnite_chronology_attalus"),
            "Ancient traditions disagree between a drawn battle and a Roman defeat; the HCED Samnite-win result is not promoted without adjudication.",
        ),
        _hold(
            (
                "hced-Lake Vadimo-310-1",
                "466e056970f9dd87de0501dbf8682782b984d781b430eee4106713d81dcc6e57",
                8885,
                "Lake Vadimo",
                -310,
                -310,
                "Rome",
                "Samnites, Etruria",
                "Rome",
                "Samnites, Etruria",
            ),
            "samnite_wars",
            "coalition_or_party_gap",
            True,
            _SAMNITE_EVIDENCE,
            "The losing side is a composite Samnite-Etruscan coalition and cannot inherit one confederation identity.",
        ),
        _hold(
            (
                "hced-Camerinum-295-1",
                "b9f0cffc91435389c267b6ad71eaa40d11d6de8b34b685cad3299bcaa17f59f3",
                2985,
                "Camerinum",
                -295,
                -295,
                "Samnites, Gauls",
                "Rome",
                "Samnites, Gauls",
                "Rome",
            ),
            "samnite_wars",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_samnium_cambridge", "wave7_p2_sentinum_cambridge"),
            "The winning side combines Samnite and Gallic forces; both coalition members require explicit identities.",
        ),
        _hold(
            (
                "hced-Sentinum-295-1",
                "abcf4a717cc22434ececbae5a2552e43750cfbddb30398d5cdf294eab119affb",
                14535,
                "Sentinum",
                -295,
                -295,
                "Rome",
                "Samnites",
                "Rome",
                "Samnites",
            ),
            "samnite_wars",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_sentinum_livy", "wave7_p2_sentinum_cambridge"),
            "The raw row omits the documented Gallic coalition partner and therefore does not represent the complete opposing side.",
        ),
        _hold(
            (
                "hced-Teanum-90-1",
                "85ef6ccf7c63f7697b8c1b4e7fc49caf966aab53344ffb8d1834d741270b28d4",
                15717,
                "Teanum",
                -90,
                -90,
                "Marsi, Samnites",
                "Rome",
                "Marsi, Samnites",
                "Rome",
            ),
            "samnite_social_war",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_social_war_appian",),
            "The winning Social War side combines Marsic and Samnite actors that must remain separate.",
        ),
        _hold(
            (
                "hced-Asculum, Marche-89-1",
                "a4108c0d0f249db01074d57e3cfeb09fe64451bc3615a9e8a21879fd5301c21c",
                1183,
                "Asculum, Marche",
                -89,
                -89,
                "Rome",
                "Samnite Rebels, Marsi Rebels",
                "Rome",
                "Samnite Rebels, Marsi Rebels",
            ),
            "samnite_social_war",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_social_war_appian",),
            "The losing Social War side combines explicitly distinct Samnite and Marsic insurgents.",
        ),
        _hold(
            (
                "hced-Fucine Lake-89-1",
                "8337b1006997715afabf115ea980d2ca054bfdb987c9e90bea48eadcc8fbd219",
                5883,
                "Fucine Lake",
                -89,
                -89,
                "Marsi, Samnites",
                "Rome",
                "Marsi, Samnites",
                "Rome",
            ),
            "samnite_social_war",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_social_war_appian",),
            "The winning Social War side combines Marsic and Samnite actors that must remain separate.",
        ),
        _hold(
            (
                "hced-Pompeii-89-1",
                "cab53e7e55fc77ae568e80fe29255e0e99bb561e72220bb8ef2337551a0edd16",
                12689,
                "Pompeii",
                -89,
                -89,
                "Rome",
                "Marsi, Samnites",
                "Rome",
                "Marsi, Samnites",
            ),
            "samnite_social_war",
            "coalition_or_party_gap",
            True,
            ("wave7_p2_social_war_appian",),
            "The losing Social War side combines Marsic and Samnite actors that must remain separate.",
        ),
        _hold(
            (
                "hced-Kruje, Albania1448-1",
                "5bebcd1c766b98ad3e5295dd17a0f6cfd50936b828fd07c1c2262165350a5791",
                8641,
                "Kruje, Albania",
                1448,
                1448,
                "Albania",
                "Ottoman Empire",
                "Albania",
                "Ottoman Empire",
            ),
            "albania_lezhe",
            "chronology_or_duplicate",
            True,
            _LEZHE_EVIDENCE,
            "The official chronology places Svetigrad in 1448 and the first siege of Kruje in 1450; this row is likely misdated or duplicative.",
        ),
        _hold(
            (
                "hced-Gaeta1860-1",
                "170376ef86d9149839c92d5c410e5d1ba8b978f46c2a31bce1b9ff013c027f6d",
                5925,
                "Gaeta",
                1860,
                1860,
                "Piedmont",
                "Naples",
                "Piedmont",
                "Naples",
            ),
            "piedmont_sardinia",
            "cross_year_chronology",
            True,
            ("wave7_p2_gaeta_cambridge",),
            "The siege began in November 1860 but its decisive surrender occurred in February 1861; the one-year row needs correction.",
        ),
        _hold(
            (
                "hced-Albania1939-1",
                "2c8783b8dc1c283e150a27890a16441256bf59f4ca2c457132c6c6bb45463fae",
                359,
                "Albania",
                1939,
                1939,
                "Italy",
                "Albania",
                "Italy",
                "Albania",
            ),
            "albania_1939",
            "published_duplicate",
            False,
            (),
            "The candidate is already represented by published release event hced_label_hced_albania1939_1 and must not be rated twice.",
        ),
    ]
}


# Generic policies remain intentionally narrow; candidate-keyed holds take priority.
WAVE7_CENTRAL_PASS2_LABEL_WINDOWS: dict[
    str, tuple[tuple[int, int, tuple[str, ...]], ...]
] = {
    "piedmont": ((1721, 1860, _PIEDMONT),),
    "albania": ((1444, 1468, _LEZHE),),
    "arab rebels": ((1916, 1919, _ARAB_REVOLT),),
    "samnites": ((-343, -290, _SAMNITE_WARS), (-91, -88, _SAMNITE_SOCIAL)),
    "samnite rebels": ((-91, -88, _SAMNITE_SOCIAL),),
}


WAVE7_CENTRAL_PASS2_TRANSITION_YEAR_HOLDS: dict[str, frozenset[int]] = {
    "piedmont": frozenset({1720, 1861}),
    "albania": frozenset({1385, 1939}),
    "arab rebels": frozenset({1889}),
    "samnites": frozenset(),
    "samnite rebels": frozenset(),
}


WAVE7_CENTRAL_PASS2_FINAL_AUDIT_SIGNATURE = (
    "1b80ab5a498c802125f0870864a90d14f64aa72243acbaa08b0f5bb3ffeccd01"
)
