from __future__ import annotations

"""Lane-local entity boundaries and direct evidence sources for Wave 6 C."""

from typing import Any


def _source(
    source_id: str,
    authority: str,
    supports: str,
    url: str,
) -> dict[str, Any]:
    return {
        "id": source_id,
        "title": supports,
        "url": url,
        "publisher": authority,
        "license": "Citation and link only",
        "source_type": "official_or_academic_reference",
        "accessed": "2026-07-15",
        "source_family_id": f"wave6_1800_2021_{source_id}",
        "evidence_roles": ["identity_boundary", "party_and_outcome_adjudication"],
    }


WAVE6_1800_2021_SOURCES = [
    _source(
        "philippines_loc_chronology",
        "Library of Congress",
        "Philippine conflict chronology, 1896-1902",
        "https://guides.loc.gov/world-of-1898/chronology",
    ),
    _source(
        "philippines_army_cmh",
        "U.S. Army Center of Military History",
        "Philippine-American War campaign chronology",
        "https://history.army.mil/Research/Reference-Topics/Army-Campaigns/Brief-Summaries/Philippine-Insurrection/",
    ),
    _source(
        "philippines_nhcp_binakayan",
        "National Historical Commission of the Philippines",
        "Binakayan and Zapote actions",
        "https://nhcp.gov.ph/meseums/mba/",
    ),
    _source(
        "philippines_nhcp_imus",
        "National Historical Commission of the Philippines",
        "Imus revolutionary occupation and Spanish recapture",
        "https://philhistoricsites.nhcp.gov.ph/registry_database/imus/",
    ),
    _source(
        "philippines_nhcp_tirad",
        "National Historical Commission of the Philippines",
        "Tirad Pass parties, date, and result",
        "https://philhistoricsites.nhcp.gov.ph/registry_database/battle-of-tirad-pass/",
    ),
    _source(
        "philippines_nhcp_zapote",
        "National Historical Commission of the Philippines",
        "Zapote identity and outcome",
        "https://philhistoricsites.nhcp.gov.ph/registry_database/labanan-sa-zapote/",
    ),
    _source(
        "mexico_constitutionalists",
        "Government of Mexico",
        "Constitutionalist movement from Guadalupe to Teoloyucan",
        "https://www.constitucion1917.gob.mx/es/Constitucion1917/Revolucion_Constitucionalista",
    ),
    _source(
        "mexico_orendain",
        "Mexico Secretariat of Culture",
        "Orendain parties and Constitutionalist victory",
        "https://www.cultura.gob.mx/centenario-ejercito/batalla_orendain.php/batalla_cd_juarez.php",
    ),
    _source(
        "mexico_torreon",
        "Mexico Secretariat of Culture",
        "1914 Torreon parties and outcome",
        "https://www.cultura.gob.mx/centenario-ejercito/batalla_torreon.php",
    ),
    _source(
        "mexico_zacatecas",
        "Mexico Secretariat of National Defense",
        "Zacatecas battle outcome",
        "https://www.gob.mx/defensa/documentos/23-de-junio-de-1914-batalla-de-zacatecas",
    ),
    _source(
        "mahdist_nam",
        "National Army Museum",
        "British, Egyptian, and Mahdist party distinctions",
        "https://www.nam.ac.uk/explore/egypt-and-sudan",
    ),
    _source(
        "mahdist_bm",
        "British Museum",
        "Mahdiya identity context",
        "https://www.britishmuseum.org/collection/term/x105338",
    ),
    _source(
        "zulu_nam",
        "National Army Museum",
        "Anglo-Zulu War parties and outcomes",
        "https://www.nam.ac.uk/explore/zulu-war",
    ),
    _source(
        "nguyen_vnmh",
        "Vietnam National Museum of History",
        "Nguyen state boundary and colonial transition",
        "https://vnmh.com.vn/en/Articles/4205/the-nguyen-dynasty-1802-1945-ad",
    ),
    _source(
        "nguyen_musee_armee",
        "Musee de l'Armee",
        "French conquest chronology in Vietnam",
        "https://www.musee-armee.fr/ExpoIndochine/1859-1907.html",
    ),
    _source(
        "carlist_spanish_army",
        "Spanish Army",
        "Third Carlist War chronology",
        "https://ejercito.defensa.gob.es/en/unidades/Cordoba/brimzx_guzmanelbueno/Organizacion/RI_N.2/index.html",
    ),
    _source(
        "carlist_governments",
        "Spanish Army",
        "Spanish government transitions during the Third Carlist War",
        "https://ejercito.defensa.gob.es/Galerias/Descarga_pdf/Unidades/Madrid/rinf1/LIBRO_HISTORIA_DEL_INMEMORIAL_DEL_REY_NUEVO_-_DR.GUILLERMO_CALLEJA_LEAL.pdf",
    ),
    _source(
        "bulgaria_usni",
        "U.S. Naval Institute",
        "First Balkan War parties and chronology",
        "https://www.usni.org/magazines/proceedings/1913/march/notes-balkan-war",
    ),
    _source(
        "bulgaria_iwm",
        "Imperial War Museums",
        "Salonika campaign parties and outcomes",
        "https://www.iwm.org.uk/history/a-short-history-of-the-salonika-campaign",
    ),
    _source(
        "turkiye_culture_adrianople_1913",
        "Republic of Turkiye Ministry of Culture and Tourism",
        "Ottoman recapture of Edirne in July 1913",
        "https://www.ktb.gov.tr/EN-117904/edirne.html",
    ),
    _source(
        "saxony_kobryn",
        "Borodino Panorama Museum",
        "Kobryn Russian victory over Saxon forces",
        "https://www.1812panorama.ru/hg/hg_hist13.html",
    ),
    _source(
        "saxony_maubeuge",
        "Napoleon Series academic edition",
        "Maubeuge siege chronology",
        "https://www.napoleon-series.org/military-info/battles/1814/Weil/Volume4/Weil19b.pdf",
    ),
    _source(
        "roman_republic_italian_army",
        "Italian Army",
        "Roman Republic, Palestrina, and Rome actors and results",
        "https://www.esercito.difesa.it/storia/giuseppe-garibaldi/83206.html",
    ),
    _source(
        "arab_israeli_1948_state",
        "U.S. Department of State Office of the Historian",
        "1948 Arab-Israeli War parties and strategic result",
        "https://history.state.gov/milestones/1945-1952/arab-israeli-war",
    ),
    _source(
        "six_day_state",
        "U.S. Department of State Office of the Historian",
        "Six-Day War parties, fronts, and outcome",
        "https://history.state.gov/historicaldocuments/frus1964-68v19/summary",
    ),
    _source(
        "chad_un_yearbook",
        "United Nations",
        "1987 Chad-Libya conflict chronology and outcomes",
        "https://digitallibrary.un.org/nanna/record/143313/files/278477-EN.pdf?registerDownload=1&version=1&withMetadata=0&withWatermark=0",
    ),
]


def _entity(
    entity_id: str,
    name: str,
    kind: str,
    start_year: int,
    end_year: int | None,
    region: str,
    source_ids: tuple[str, ...],
) -> dict[str, Any]:
    return {
        "id": entity_id,
        "name": name,
        "kind": kind,
        "start_year": start_year,
        "end_year": end_year,
        "region": region,
        "aliases": [],
        "predecessors": [],
        "continuity_note": (
            "Exact Wave 6 reviewed-party boundary. It is used only by candidate-specific "
            "contracts and opens no label or code fallback. Predecessor and successor "
            "ratings are not inherited."
        ),
        "source_ids": list(source_ids),
    }


WAVE6_1800_2021_ENTITY_OVERRIDES = [
    _entity(
        "philippine_revolutionary_forces",
        "Philippine Revolutionary Forces",
        "revolutionary_force",
        1896,
        1898,
        "Southeast Asia",
        ("philippines_loc_chronology",),
    ),
    _entity(
        "first_philippine_republic",
        "First Philippine Republic",
        "republic",
        1899,
        1902,
        "Southeast Asia",
        ("philippines_loc_chronology", "philippines_army_cmh"),
    ),
    _entity(
        "constitutionalist_army_mexico",
        "Constitutionalist Army of Mexico",
        "revolutionary_force",
        1913,
        1914,
        "North America",
        ("mexico_constitutionalists",),
    ),
    _entity(
        "huerta_federal_army",
        "Mexican Federal Army under Huerta",
        "state_force",
        1913,
        1914,
        "North America",
        ("mexico_constitutionalists",),
    ),
    _entity(
        "mahdist_ansar_forces",
        "Mahdist Ansar Forces",
        "state_force",
        1881,
        1899,
        "Northeast Africa",
        ("mahdist_nam", "mahdist_bm"),
    ),
    _entity(
        "zulu_kingdom",
        "Zulu Kingdom",
        "kingdom",
        1816,
        1897,
        "Southern Africa",
        ("zulu_nam",),
    ),
    _entity(
        "nguyen_dai_nam",
        "Nguyen Dai Nam",
        "dynastic_state",
        1802,
        1885,
        "Southeast Asia",
        ("nguyen_vnmh",),
    ),
    _entity(
        "spanish_isabelline_monarchy",
        "Spanish Monarchy under Isabella II",
        "kingdom",
        1833,
        1868,
        "Southern Europe",
        ("carlist_governments",),
    ),
    _entity(
        "kingdom_spain_amadeo_i",
        "Kingdom of Spain under Amadeo I",
        "kingdom",
        1870,
        1873,
        "Southern Europe",
        ("carlist_governments",),
    ),
    _entity(
        "first_spanish_republic",
        "First Spanish Republic",
        "republic",
        1873,
        1874,
        "Southern Europe",
        ("carlist_governments",),
    ),
    _entity(
        "third_carlist_army",
        "Third Carlist Army",
        "civil_war_faction",
        1872,
        1876,
        "Southern Europe",
        ("carlist_spanish_army",),
    ),
    _entity(
        "principality_bulgaria",
        "Principality of Bulgaria",
        "principality",
        1878,
        1908,
        "Southeast Europe",
        ("bulgaria_usni",),
    ),
    _entity(
        "kingdom_bulgaria",
        "Kingdom of Bulgaria",
        "kingdom",
        1908,
        1946,
        "Southeast Europe",
        ("bulgaria_usni", "bulgaria_iwm"),
    ),
    _entity(
        "kingdom_saxony",
        "Kingdom of Saxony",
        "kingdom",
        1806,
        1918,
        "Central Europe",
        ("saxony_kobryn", "saxony_maubeuge"),
    ),
    _entity(
        "second_french_republic",
        "French Second Republic",
        "republic",
        1848,
        1852,
        "Western Europe",
        ("roman_republic_italian_army",),
    ),
    _entity(
        "roman_republic_1849",
        "Roman Republic of 1849",
        "republic",
        1849,
        1849,
        "Southern Europe",
        ("roman_republic_italian_army",),
    ),
    _entity(
        "kingdom_two_sicilies",
        "Kingdom of the Two Sicilies",
        "kingdom",
        1816,
        1861,
        "Southern Europe",
        ("roman_republic_italian_army",),
    ),
    _entity(
        "kingdom_montenegro",
        "Kingdom of Montenegro",
        "kingdom",
        1910,
        1918,
        "Southeast Europe",
        ("bulgaria_usni",),
    ),
    _entity(
        "lebanese_republic",
        "Lebanese Republic",
        "republic",
        1943,
        None,
        "West Asia",
        ("arab_israeli_1948_state",),
    ),
    _entity(
        "republic_chad",
        "Republic of Chad",
        "republic",
        1960,
        None,
        "Central Africa",
        ("chad_un_yearbook",),
    ),
    _entity(
        "libyan_arab_jamahiriya",
        "Libyan Arab Jamahiriya",
        "state",
        1977,
        2011,
        "North Africa",
        ("chad_un_yearbook",),
    ),
    # Existing Wave 5 series are reused and widened atomically; no parallel line is created.
    _entity(
        "egypt_muhammad_ali",
        "Egypt",
        "state",
        1805,
        None,
        "North Africa",
        ("mahdist_nam", "arab_israeli_1948_state", "six_day_state"),
    ),
    _entity(
        "clio_q801_1948_5abea45e",
        "State of Israel",
        "state",
        1948,
        None,
        "West Asia",
        ("arab_israeli_1948_state", "six_day_state"),
    ),
    _entity(
        "clio_q810_1947_98de647a",
        "Jordan",
        "state",
        1947,
        None,
        "West Asia",
        ("arab_israeli_1948_state",),
    ),
    _entity(
        "clio_q41137_1973_b05dea50",
        "Syria",
        "state",
        1946,
        None,
        "West Asia",
        ("arab_israeli_1948_state", "six_day_state"),
    ),
]

WAVE6_REUSED_CANONICAL_ENTITY_IDS = frozenset(
    {
        "clio_it_italian_k_587_7218f0c7",
        "clio_q801_1948_5abea45e",
        "clio_q810_1947_98de647a",
        "clio_q41137_1973_b05dea50",
        "egypt_muhammad_ali",
        "kingdom_iraq",
        "spanish_empire",
    }
)
