"""Audited static contracts for the Wave 7 Global/South promotion lane."""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any


WAVE7_GLOBAL_BASE_COMMIT = "e523a3b46c766c2952b7f0aa27f8e76f9d51d107"
WAVE7_GLOBAL_FINAL_AUDIT_SIGNATURE = (
    "7da16e99b2d1b8f99aa760c5d58e5a39007114dc34e79dec140cd8d51af0ae3f"
)

_HCED_FIELDS = (
    "candidate_id",
    "source_record_id",
    "source_row",
    "source_snapshot",
    "name",
    "year_low",
    "year_high",
    "side_1_raw",
    "side_2_raw",
    "winner_raw",
    "loser_raw",
    "participants_raw",
    "war_names",
    "consulted_source_raw",
    "duplicate_source_id",
    "seshat_side_1_candidates",
    "seshat_side_2_candidates",
    "theatre_raw",
    "scale_raw",
    "scale_inferred_raw",
    "latitude",
    "longitude",
    "modern_location_country",
)
_HCED_VALUE_FIELDS = (
    "candidate_id",
    "source_row",
    "name",
    "year_low",
    "side_1_raw",
    "side_2_raw",
    "winner_raw",
    "participants_raw",
    "war_names",
    "consulted_source_raw",
    "seshat_side_1_candidates",
    "seshat_side_2_candidates",
    "theatre_raw",
    "scale_raw",
    "scale_inferred_raw",
    "latitude",
    "longitude",
    "modern_location_country",
)
_HCED_SOURCE_SNAPSHOT = "data/raw/hced/20260713T161517Z-92a22e49c20d.csv"
_HCED_ROW_VALUES = (
    (
        "hced-Alexandria-48-1",
        447,
        "Alexandria",
        -48,
        "Rome",
        "Egypt",
        "Rome",
        ["Egypt", "Alexandria", "Egyptian", "Roman"],
        ["Wars of the First Triumvirate"],
        None,
        ["it_roman_rep_3"],
        [],
        "Land",
        None,
        None,
        "31.2000924",
        "29.9187387",
        "Egypt",
    ),
    (
        "hced-Alexandria1167-1",
        455,
        "Alexandria",
        1167,
        "Kingdom of Jerusalem",
        "Egypt",
        "Kingdom of Jerusalem",
        ["Egypt", "Cairo", "Jerusalem"],
        ["Crusader Invasion of Egypt"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.2000924",
        "29.9187387",
        "Egypt",
    ),
    (
        "hced-Antukyah1531-1",
        879,
        "Antukyah",
        1531,
        "Adal Sultanate",
        "Ethiopia",
        "Adal Sultanate",
        [],
        ["Ethiopian-Adal War"],
        "Encyclopedia of Warfare, Showalter, 2014, p321",
        [],
        [],
        "Land",
        "3",
        None,
        "11.0212514",
        "39.475692",
        "Ethiopia",
    ),
    (
        "hced-Ascalon1123-1",
        1167,
        "Ascalon",
        1123,
        "Venice",
        "Egypt",
        "Venice",
        [
            "Crusader-Muslim",
            "Venice",
            "Palestine",
            "Egyptian",
            "Muslim",
            "Palestine",
            "Venetians",
        ],
        ["Crusader-Muslim Wars"],
        None,
        [],
        [],
        "Sea",
        None,
        None,
        "31.6687885",
        "34.5742523",
        "Israel",
    ),
    (
        "hced-Asluj1948-1",
        1215,
        "Asluj",
        1948,
        "Israel",
        "Egypt",
        "Israel",
        [],
        ["Israeli War of Independence"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.015695",
        "34.760799",
        "Israel",
    ),
    (
        "hced-Barrancas1819-1",
        1737,
        "Barrancas",
        1819,
        "Argentine Rebels",
        "Argentine Government",
        "Argentine Rebels",
        ["Argentine", "Barrancas", "Irish", "Santa"],
        ["Argentine Civil Wars"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "-32.2356023",
        "-60.9916137",
        "Argentina",
    ),
    (
        "hced-Beersheba1948-1",
        1921,
        "Beersheba",
        1948,
        "Israel",
        "Egypt",
        "Israel",
        ["Egyptian", "Israeli", "Negev"],
        ["Israeli War"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.252973",
        "34.791462",
        "Israel",
    ),
    (
        "hced-Belmont, South Africa1899-1",
        2015,
        "Belmont, South Africa",
        1899,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["South Africa", "British", "Belmont"],
        ["2nd Anglo-Boer War"],
        "The Boer War, Thomas Pakenham, 1979, Chapter 16",
        ["gb_british_emp_2"],
        [],
        "Land",
        "2",
        None,
        "-29.4118742",
        "24.3638509",
        "South Africa",
    ),
    (
        "hced-Biddulphsberg1900-1",
        2175,
        "Biddulphsberg",
        1900,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Bloemfontein", "Senekal", "Senekal", "British"],
        ["2nd Anglo-Boer War"],
        None,
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        "1",
        "-28.268082",
        "27.768867",
        "South Africa",
    ),
    (
        "hced-Boomplaats1848-1",
        2389,
        "Boomplaats",
        1848,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["British", "British", "Hopetown", "British"],
        ["Orange Free State War"],
        None,
        ["gb_british_emp_1"],
        [],
        "Land",
        None,
        None,
        "-29.8391587",
        "23.8880978",
        "South Africa",
    ),
    (
        "hced-Bothaville1900-1",
        2449,
        "Bothaville",
        1900,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["British", "Bothaville", "Roodewal"],
        ["Anglo-Boer War"],
        "Encyclopedia of Warfare, Showalter, 2014, p720",
        ["gb_british_emp_2"],
        [],
        "Land",
        "1",
        None,
        "-27.3740206",
        "26.5849391",
        "South Africa",
    ),
    (
        "hced-Cerrito1812-1",
        3401,
        "Cerrito",
        1812,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Spanish"],
        ["Argentine War of Independence"],
        "Encyclopedia of Warfare, Showalter, 2014, p561",
        [],
        ["es_spanish_emp_2"],
        "Land",
        "1",
        None,
        "-34.8492653",
        "-56.1877836",
        "Uruguay",
    ),
    (
        "hced-Damietta1218-1",
        4469,
        "Damietta",
        1249,
        "Egypt",
        "France",
        "Egypt",
        ["France", "Cyprus", "Egypt", "French", "Mansura"],
        ["7th Crusade"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.4175388",
        "31.8144434",
        "Egypt",
    ),
    (
        "hced-Driefontein1900-1",
        4931,
        "Driefontein",
        1900,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["British"],
        ["2nd Anglo-Boer War"],
        "Clodfelter, Warfare and Armed Conflict, p211",
        ["gb_british_emp_2"],
        [],
        "Land",
        "2",
        None,
        "-27.0064537",
        "30.4242401",
        "South Africa",
    ),
    (
        "hced-Elands River Poort1901-1",
        5147,
        "Elands River Poort",
        1901,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Lancers", "Tarskastad", "British"],
        ["2nd Anglo-Boer War"],
        "The Boer War, Pakenham, 1979, Chapter 40",
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        None,
        "-31.850833",
        "26.1655893",
        "South Africa",
    ),
    (
        "hced-Faluja1948-1",
        5427,
        "Faluja",
        1948,
        "Egypt",
        "Israel",
        "Egypt",
        [],
        ["Israeli War of Independence"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.6095813",
        "34.74192",
        "Israel",
    ),
    (
        "hced-Fariskur1250-1",
        5443,
        "Fariskur",
        1250,
        "Egypt",
        "France",
        "Egypt",
        ["Cairo", "Mansura", "Egypt"],
        ["7th Crusade"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "31.3272385",
        "31.7172872",
        "Egypt",
    ),
    (
        "hced-Florida, Bolivia1814-1",
        5569,
        "Florida, Bolivia",
        1814,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        [
            "Florida",
            "Bolivia",
            "Santa Cruz",
            "Bolivia",
            "Argentine",
            "Spanish",
            "Royalist",
            "Florida",
            "Santa",
        ],
        ["Argentine War of Independence"],
        None,
        [],
        ["es_spanish_emp_2"],
        "Land",
        None,
        None,
        "-18.1363597",
        "-63.8640569",
        "Bolivia",
    ),
    (
        "hced-Graspan1899-1",
        6383,
        "Graspan",
        1899,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["British", "Belmont", "British"],
        ["2nd Anglo-Boer War"],
        "Harbottle's Dictionary of Battles, George Bruce, 1979, p106",
        ["gb_british_emp_2"],
        [],
        "Land",
        "1",
        None,
        "-30.1",
        "22.4833329",
        "South Africa",
    ),
    (
        "hced-Kadesh-1275-1",
        7863,
        "Kadesh",
        -1275,
        "Egypt",
        "Hittites",
        "Egypt",
        ["Egyptian", "Egypt", "Syria", "Hittites", "Ka-", "Orontes", "Hims"],
        ["Egyptian-Hittite Wars"],
        'An Encyclopedia of Battles, Eggenberger, p214. Hutchinsons Dictionary of Ancient and Medieval Warfare, "Kadesh, Battle of"',
        [],
        [],
        "Land",
        "3",
        None,
        "34.5550765",
        "36.5182347",
        "Syria",
    ),
    (
        "hced-Karee Siding1900-1",
        8047,
        "Karee Siding",
        1900,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["Kareehalte"],
        ["2nd Anglo-Boer War"],
        "A division implies a scale of 2",
        ["gb_british_emp_2"],
        [],
        "Land",
        "2",
        "1",
        "-28.86278",
        "26.3638899",
        "South Africa",
    ),
    (
        "hced-Kimberely1899-1",
        8381,
        "Kimberely",
        1899,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        [],
        ["2nd Anglo-Boer War"],
        "The Boer War, Thomas Pakenham, 1979, Chapter 16",
        ["gb_british_emp_2"],
        [],
        "Land",
        "2",
        None,
        "-28.7282384",
        "24.7499112",
        "South Africa",
    ),
    (
        "hced-La Herradura1819-1",
        8827,
        "La Herradura",
        1819,
        "Argentinian Government",
        "Argentine Rebels",
        "Argentinian Government",
        ["Argentine", "Indians", "Irish", "Barrancas"],
        ["Argentine Civil Wars"],
        None,
        [],
        [],
        "Land",
        None,
        None,
        "-32.5393323",
        "-63.2025642",
        "Argentina",
    ),
    (
        "hced-Las Piedras1811-1",
        9019,
        "Las Piedras",
        1811,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        [
            "Las Piedras",
            "Montevideo",
            "Uruguay",
            "Las",
            "Spanish",
            "Artigas",
            "Portuguese",
        ],
        ["Argentine War of Independence"],
        None,
        [],
        ["es_spanish_emp_2"],
        "Land",
        None,
        None,
        "-34.716667",
        "-56.216667",
        "Uruguay",
    ),
    (
        "hced-Lindley1900-1",
        9275,
        "Lindley",
        1900,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["British", "Pretoria", "Irish"],
        ["2nd Anglo-Boer War"],
        None,
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        "1",
        "-27.9008809",
        "27.9131832",
        "South Africa",
    ),
    (
        "hced-Martin Garcia1814-1",
        10061,
        "Martin Garcia",
        1814,
        "Spain",
        "Argentine Rebels",
        "Spain",
        ["Spanish", "American", "Spanish", "China"],
        ["Argentine War             of Independence"],
        None,
        ["es_spanish_emp_2"],
        [],
        "Sea",
        None,
        None,
        "-34.1824176",
        "-58.2595699",
        "Argentina",
    ),
    (
        "hced-Montevideo1814-1",
        10733,
        "Montevideo",
        1814,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        [],
        ["Argentine War    of Independence"],
        "Clodfelter, Warfare and Armed Conflict, p309",
        [],
        ["es_spanish_emp_2"],
        "Land",
        "1",
        "1",
        "-34.9011127",
        "-56.1645314",
        "Uruguay",
    ),
    (
        "hced-Pari1816-1",
        12187,
        "Pari",
        1816,
        "Spain",
        "Argentine Rebels",
        "Spain",
        ["Spain", "Bolivia", "Argentine", "Santa Cruz", "Florida"],
        ["Argentine War of Independence"],
        None,
        ["es_spanish_emp_3"],
        [],
        "Land",
        None,
        None,
        "-18.0084789",
        "-64.8608672",
        "Bolivia",
    ),
    (
        "hced-Pelusium-525-1",
        12317,
        "Pelusium",
        -525,
        "Persia",
        "Egypt",
        "Persia",
        ["Persian", "Egypt", "Persia", "Egypt", "Memphis", "Egypt", "Persian"],
        ["Persian Invasion of Egypt"],
        None,
        ["ir_archaemenid_emp"],
        [],
        "Land",
        None,
        None,
        "31.042591",
        "32.539981",
        "Egypt",
    ),
    (
        "hced-Puesto del Marquez1815-1",
        12945,
        "Puesto del Marquez",
        1815,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Argentina", "Jujuy", "Venta"],
        ["Argentine War of Independence"],
        None,
        [],
        ["es_spanish_emp_3"],
        "Land",
        None,
        None,
        "-22.5379665",
        "-65.702172",
        "Argentina",
    ),
    (
        "hced-Pyramids1798-1",
        13011,
        "Pyramids",
        1798,
        "France",
        "Egypt",
        "France",
        ["French", "Egypt", "Mamluk", "Cairo"],
        ["French Revolutionary Wars (Middle East)f"],
        "The Field and the Forge, Landers, p390",
        [],
        [],
        "Land",
        "3",
        None,
        "29.9792345",
        "31.1342019",
        "Egypt",
    ),
    (
        "hced-Reddersburg1900-1",
        13273,
        "Reddersburg",
        1900,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Reddersburg", "Bloemfontein"],
        ["2nd Anglo-Boer Wars"],
        "Clodfelter, Warfare and Armed Conflict, p211",
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        "1",
        "-29.6562102",
        "26.1891142",
        "South Africa",
    ),
    (
        "hced-Rietfontein1899-1",
        13383,
        "Rietfontein",
        1899,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["British", "Rietfontein", "Yules"],
        ["2nd Anglo-Boer War"],
        "Harbottle's Dictionary of Battles, George Bruce, 1979, p213",
        ["gb_british_emp_2"],
        [],
        "Land",
        "1",
        None,
        "-25.7090736",
        "28.2204987",
        "South Africa",
    ),
    (
        "hced-Rio Piedras1812-1",
        13437,
        "Rio Piedras",
        1812,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Spanish", "Metan"],
        ["Argentine War of Independence"],
        None,
        [],
        ["es_spanish_emp_2"],
        "Land",
        None,
        None,
        "-25.3141417",
        "-64.9147354",
        "Argentina",
    ),
    (
        "hced-Roodewal, Orange Free State1900-1",
        13547,
        "Roodewal, Orange Free State",
        1900,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Johannesburg"],
        ["2nd Anglo-Boer War"],
        None,
        [],
        ["gb_british_emp_2"],
        "Land",
        None,
        None,
        "-24.14819",
        "31.6344276",
        "South Africa",
    ),
    (
        "hced-Salta1813-1",
        13951,
        "Salta",
        1813,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Argentina", "Spanish", "Salta", "Vilcapugio"],
        ["Argentine War of Independence"],
        "Encyclopedia of Warfare, Showalter, 2014, p561",
        [],
        ["es_spanish_emp_2"],
        "Land",
        "1",
        None,
        "-24.7821269",
        "-65.4231976",
        "Argentina",
    ),
    (
        "hced-San Ignacio1867-1",
        14079,
        "San Ignacio",
        1867,
        "Argentina",
        "Argentine Rebels",
        "Argentina",
        [
            "Argentine",
            "Argentina",
            "San       Ignacio",
            "Rio Quinto",
            "San Luis",
            "Chile",
            "Arredondo",
        ],
        ["Argentine Civil Wars"],
        "Clodfelter, Warfare and Armed Conflict, p320",
        ["ar_argentina_rep_1"],
        [],
        "Land",
        "1",
        None,
        "-33.0386998",
        "-66.4362808",
        "Argentina",
    ),
    (
        "hced-San Lorenzo, Argentina1813-1",
        14117,
        "San Lorenzo, Argentina",
        1813,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["San Lorenzo", "Argentina", "Spanish", "Royalist", "Zabala", "San Lorenzo"],
        ["Argentine War of Independence"],
        None,
        [],
        ["es_spanish_emp_2"],
        "Land and Sea",
        "1",
        "1",
        "-32.9357045",
        "-60.686889",
        "Argentina",
    ),
    (
        "hced-San Nicolas1811-1",
        14149,
        "San Nicolas",
        1811,
        "Spain",
        "Argentine Rebels",
        "Spain",
        [],
        ["Argentine War of Independence"],
        None,
        ["es_spanish_emp_2"],
        [],
        "Sea",
        None,
        None,
        "-32.9621145",
        "-61.3222443",
        "Argentina",
    ),
    (
        "hced-Stormberg1899-1",
        15251,
        "Stormberg",
        1899,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["British", "Queenstown", "Magersfontein"],
        ["2nd Anglo-Boer War"],
        "Osprey Guide to the Boer War 1899-1902, Gregory Fremont-Barnes, p61",
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        None,
        "-31.2984459",
        "26.2522263",
        "South Africa",
    ),
    (
        "hced-Suipacha1810-1",
        15315,
        "Suipacha",
        1810,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Spain", "Spanish", "Tupiza", "Bolivia"],
        ["Argentine War of Independence"],
        "Encyclopedia of Warfare, Showalter, 2014, p560",
        [],
        ["es_spanish_emp_2"],
        "Land",
        "1",
        None,
        "-21.6083297",
        "-65.7079169",
        "Argentina",
    ),
    (
        "hced-Tucuman1812-1",
        16333,
        "Tucuman",
        1812,
        "Argentine Rebels",
        "Spain",
        "Argentine Rebels",
        ["Upper", "Peru", "Huaqui", "Spanish"],
        ["Argentine War of Independence"],
        "Encyclopedia of Warfare, Showalter, 2014, p561",
        [],
        ["es_spanish_emp_2"],
        "Land",
        "1",
        None,
        "-26.8328072",
        "-65.2926342",
        "Argentina",
    ),
    (
        "hced-Tweefontein1901-1",
        16421,
        "Tweefontein",
        1901,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Britain", "Tweefontein", "Yeomanry"],
        ["2nd Anglo-Boer War"],
        None,
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        None,
        "-25.3468559",
        "28.8334623",
        "South Africa",
    ),
    (
        "hced-Venta1815-1",
        16733,
        "Venta",
        1815,
        "Spain",
        "Argentine Rebels",
        "Spain",
        ["Argentine", "Puesto", "Argentine", "Media", "Oruro", "Bolivia"],
        ["Argentine War of Independence"],
        None,
        ["es_spanish_emp_3"],
        [],
        "Land",
        None,
        None,
        "-18.283543",
        "-67.1694847",
        "Argentina",
    ),
    (
        "hced-Vilcapugio1813-1",
        16855,
        "Vilcapugio",
        1813,
        "Spain",
        "Argentine Rebels",
        "Spain",
        ["Spanish", "Bolivia", "Vilcapugio", "Potosi"],
        ["Argentine War of Independence"],
        "Encyclopedia of Warfare, Showalter, 2014, p562",
        ["es_spanish_emp_2"],
        [],
        "Land",
        "1",
        None,
        "-19.5275808",
        "-65.7489341",
        "Bolivia",
    ),
    (
        "hced-Wepener1900-1",
        17197,
        "Wepener",
        1900,
        "United Kingdom",
        "Orange Free State",
        "United Kingdom",
        ["Reddersburg", "Wepener", "Bloemfontein"],
        ["2nd Anglo-Boer War"],
        None,
        ["gb_british_emp_2"],
        [],
        "Land",
        "1",
        None,
        "-29.7293819",
        "27.0205594",
        "South Africa",
    ),
    (
        "hced-Zilikats Nek (1st)1900-1",
        17695,
        "Zilikats Nek (1st)",
        1900,
        "Orange Free State",
        "United Kingdom",
        "Orange Free State",
        ["Pretoria"],
        ["2nd Anglo-Boer War"],
        "1",
        [],
        ["gb_british_emp_2"],
        "Land",
        "1",
        "1",
        "-25.7052252",
        "27.8954995",
        "South Africa",
    ),
)


def _canonical_sha256(value: Any) -> str:
    payload = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _row(values: tuple[Any, ...]) -> dict[str, Any]:
    compact = dict(zip(_HCED_VALUE_FIELDS, values, strict=True))
    candidate_id = str(compact["candidate_id"])
    source_record_id = candidate_id.removeprefix("hced-").removesuffix("-1")
    side_1 = compact["side_1_raw"]
    side_2 = compact["side_2_raw"]
    winner = compact["winner_raw"]
    if winner not in {side_1, side_2}:
        raise ValueError(
            f"Wave 7 Global source outcome is not one of its sides: {candidate_id}"
        )
    expanded = {
        **compact,
        "source_record_id": source_record_id,
        "source_snapshot": _HCED_SOURCE_SNAPSHOT,
        "year_high": compact["year_low"],
        "loser_raw": side_2 if winner == side_1 else side_1,
        "duplicate_source_id": False,
    }
    return {field: expanded.get(field) for field in _HCED_FIELDS}


_ROWS = {row["candidate_id"]: row for row in map(_row, _HCED_ROW_VALUES)}

_ARGENTINE_PROMOTION_IDS = (
    "hced-Cerrito1812-1",
    "hced-Florida, Bolivia1814-1",
    "hced-Las Piedras1811-1",
    "hced-Martin Garcia1814-1",
    "hced-Montevideo1814-1",
    "hced-Pari1816-1",
    "hced-Puesto del Marquez1815-1",
    "hced-Rio Piedras1812-1",
    "hced-Salta1813-1",
    "hced-San Lorenzo, Argentina1813-1",
    "hced-San Nicolas1811-1",
    "hced-Suipacha1810-1",
    "hced-Tucuman1812-1",
    "hced-Venta1815-1",
    "hced-Vilcapugio1813-1",
)

_ORANGE_PROMOTION_IDS = (
    "hced-Biddulphsberg1900-1",
    "hced-Bothaville1900-1",
    "hced-Driefontein1900-1",
    "hced-Elands River Poort1901-1",
    "hced-Karee Siding1900-1",
    "hced-Lindley1900-1",
    "hced-Reddersburg1900-1",
    "hced-Roodewal, Orange Free State1900-1",
    "hced-Tweefontein1901-1",
    "hced-Wepener1900-1",
    "hced-Zilikats Nek (1st)1900-1",
)

_EGYPT_PROMOTION_CONFIG = {
    "hced-Alexandria-48-1": (
        "egypt_ptolemaic",
        ("roman_republic",),
        ("ptolemaic_egypt_305_bce",),
        ("met_ptolemaic_egypt",),
    ),
    "hced-Alexandria1167-1": (
        "egypt_fatimid",
        ("clio_il_jerusalem_k_1_1099_306afd1d",),
        ("clio_tn_fatimid_cal_911_d329b0b3",),
        ("met_fatimid_period",),
    ),
    "hced-Ascalon1123-1": (
        "egypt_fatimid",
        ("republic_venice",),
        ("clio_tn_fatimid_cal_911_d329b0b3",),
        ("met_fatimid_period",),
    ),
    "hced-Asluj1948-1": (
        "egypt_kingdom_1922",
        ("clio_q801_1948_5abea45e",),
        ("kingdom_egypt_1922",),
        ("egypt_sis_modern_era",),
    ),
    "hced-Beersheba1948-1": (
        "egypt_kingdom_1922",
        ("clio_q801_1948_5abea45e",),
        ("kingdom_egypt_1922",),
        ("egypt_sis_modern_era",),
    ),
    "hced-Damietta1218-1": (
        "egypt_ayyubid",
        ("clio_eg_ayyubid_sultanate_1177_95f5a3a5",),
        ("kingdom_france",),
        ("met_ayyubid_period",),
    ),
    "hced-Faluja1948-1": (
        "egypt_kingdom_1922",
        ("kingdom_egypt_1922",),
        ("clio_q801_1948_5abea45e",),
        ("egypt_sis_modern_era",),
    ),
    "hced-Fariskur1250-1": (
        "egypt_mamluk_sultanate",
        ("mamluk_sultanate",),
        ("kingdom_france",),
        ("met_mamluk_period",),
    ),
    "hced-Pelusium-525-1": (
        "egypt_saite",
        ("achaemenid_empire",),
        ("saite_egypt_664_bce",),
        ("met_saite_egypt",),
    ),
    "hced-Pyramids1798-1": (
        "egypt_mamluk_forces_1798",
        ("french_first_republic",),
        ("mamluk_egyptian_forces_1798",),
        ("met_battle_pyramids",),
    ),
}

_HOLD_CONFIG = {
    "hced-Barrancas1819-1": (
        "civil_war_faction_identity_unresolved",
        "The 1819 civil-war labels denote opposing Argentine factions, not the "
        "bounded 1810–1816 independence army.",
        ("argentina_army_1810",),
    ),
    "hced-La Herradura1819-1": (
        "civil_war_faction_identity_unresolved",
        "The 1819 civil-war labels denote opposing Argentine factions, not the "
        "bounded 1810–1816 independence army.",
        ("argentina_army_1810",),
    ),
    "hced-San Ignacio1867-1": (
        "civil_war_faction_identity_unresolved",
        "The 1867 rebel force requires a distinct faction identity and cannot "
        "inherit the 1810–1816 patriot-army rating.",
        ("argentina_army_1810",),
    ),
    "hced-Boomplaats1848-1": (
        "pre_polity_identity_anachronism",
        "The source label predates the independent Orange Free State established "
        "in 1854; it cannot be back-projected.",
        ("saho_orange_free_state",),
    ),
    "hced-Kadesh-1275-1": (
        "duplicate_and_outcome_conflict",
        "This is the already-rated Battle of Kadesh dated one year differently; "
        "its HCED outright Egyptian victory conflicts with the existing reviewed "
        "inconclusive/positional coding.",
        ("whe_kadesh",),
    ),
}

_MIGRATION_EVENT_CANDIDATES = {
    "hced_label_hced_belmont_south_africa1899_1": ("hced-Belmont, South Africa1899-1"),
    "hced_label_hced_graspan1899_1": "hced-Graspan1899-1",
    "hced_label_hced_kimberely1899_1": "hced-Kimberely1899-1",
    "hced_label_hced_rietfontein1899_1": "hced-Rietfontein1899-1",
    "hced_label_hced_stormberg1899_1": "hced-Stormberg1899-1",
}
_MIGRATION_SOURCE_EVENT_SHA256 = {
    "hced_label_hced_belmont_south_africa1899_1": (
        "4033cf495a2ffe5f116a04be63fc17795728eb9b6607b67f88df41060766530a"
    ),
    "hced_label_hced_graspan1899_1": (
        "6ccc8a78288e4ecec420c5d3859002ea5ccc7832fbe057b5d0a8c7d2683e856c"
    ),
    "hced_label_hced_kimberely1899_1": (
        "255dd3262963b2081d8cfd4d5a7611f766c39c24a62ab1e98e39908cdc70b6b8"
    ),
    "hced_label_hced_rietfontein1899_1": (
        "efb01bd5d185b93b527f4c7bef69a53028380c46faa7cf149ab33fc64aa954dd"
    ),
    "hced_label_hced_stormberg1899_1": (
        "769e8d9054317a325c193c369c1d027cc4a0117f094627ea9785b0e7136e98d2"
    ),
}
_MIGRATION_FINAL_EVENT_SHA256 = {
    "hced_label_hced_belmont_south_africa1899_1": (
        "027b3dc089ba003dd66918e0f859dbfcba91b154f5aeff79a3dcc8d358fe5f9a"
    ),
    "hced_label_hced_graspan1899_1": (
        "7e0f08b5e0a9ace632cb07106a9d63b599590d4677e3200eaa4462d5781a4e08"
    ),
    "hced_label_hced_kimberely1899_1": (
        "9f3e5c4699e2f2a2e2d4cc678f9574b130d56df025d794766d47e6cd39dbfbd9"
    ),
    "hced_label_hced_rietfontein1899_1": (
        "8e3aec6ed8ae4331a1776df4a00db830d115ce17326ed9d1fbc44a6f419da971"
    ),
    "hced_label_hced_stormberg1899_1": (
        "db4ef5d6d18cbd4a7f43710fbb6c92cbd3c04ad44fbee16f42d32bf50c25d07f"
    ),
}


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.casefold()).strip("_")


def _canonical_event(row: dict[str, Any]) -> dict[str, Any]:
    low = int(row["year_low"])
    high = int(row["year_high"])
    return {
        "canonical_key": f"{_slug(str(row['name']))}:{low}:{high}",
        "date_precision": "year",
        "granularity": "engagement",
        "name": str(row["name"]),
        "year_high": high,
        "year_low": low,
    }


WAVE7_GLOBAL_HCED_CONTRACTS: dict[str, dict[str, Any]] = {}
for _candidate_id in _ARGENTINE_PROMOTION_IDS:
    _source = _ROWS[_candidate_id]
    WAVE7_GLOBAL_HCED_CONTRACTS[_candidate_id] = {
        "audit_note": (
            "Exact independence-army window, source row, sides, and HCED tactical "
            "result reviewed."
        ),
        "canonical_event": _canonical_event(_source),
        "cohort": "rio_de_la_plata_patriot_army",
        "evidence_refs": ["argentina_army_1810", "argentina_naval_independence"],
        "raw_row": _source,
        "raw_row_sha256": _canonical_sha256(_source),
        "result": {
            "type": "win",
            "winner_side": 1 if _source["winner_raw"] == _source["side_1_raw"] else 2,
        },
        "side_1_entity_ids": [
            "rio_de_la_plata_patriot_army_1810"
            if _source["side_1_raw"] == "Argentine Rebels"
            else "spanish_empire"
        ],
        "side_2_entity_ids": [
            "rio_de_la_plata_patriot_army_1810"
            if _source["side_2_raw"] == "Argentine Rebels"
            else "spanish_empire"
        ],
    }

for _candidate_id in _ORANGE_PROMOTION_IDS:
    _source = _ROWS[_candidate_id]
    WAVE7_GLOBAL_HCED_CONTRACTS[_candidate_id] = {
        "audit_note": (
            "Exact Orange Free State 1854–1902 identity, source row, sides, and "
            "HCED tactical result reviewed."
        ),
        "canonical_event": _canonical_event(_source),
        "cohort": "orange_free_state",
        "evidence_refs": ["saho_orange_free_state", "uk_na_south_african_war"],
        "raw_row": _source,
        "raw_row_sha256": _canonical_sha256(_source),
        "result": {
            "type": "win",
            "winner_side": 1 if _source["winner_raw"] == _source["side_1_raw"] else 2,
        },
        "side_1_entity_ids": [
            "orange_free_state_1854"
            if _source["side_1_raw"] == "Orange Free State"
            else "united_kingdom"
        ],
        "side_2_entity_ids": [
            "orange_free_state_1854"
            if _source["side_2_raw"] == "Orange Free State"
            else "united_kingdom"
        ],
    }

for _candidate_id, (
    _cohort,
    _side_1,
    _side_2,
    _evidence,
) in _EGYPT_PROMOTION_CONFIG.items():
    _source = _ROWS[_candidate_id]
    WAVE7_GLOBAL_HCED_CONTRACTS[_candidate_id] = {
        "audit_note": (
            "Exact Egyptian era binding, source row, sides, and HCED tactical result "
            "reviewed; no generic Egypt alias is used."
        ),
        "canonical_event": _canonical_event(_source),
        "cohort": _cohort,
        "evidence_refs": list(_evidence),
        "raw_row": _source,
        "raw_row_sha256": _canonical_sha256(_source),
        "result": {
            "type": "win",
            "winner_side": 1 if _source["winner_raw"] == _source["side_1_raw"] else 2,
        },
        "side_1_entity_ids": list(_side_1),
        "side_2_entity_ids": list(_side_2),
    }

_source = _ROWS["hced-Antukyah1531-1"]
WAVE7_GLOBAL_HCED_CONTRACTS["hced-Antukyah1531-1"] = {
    "audit_note": (
        "Exact pre-1855 Solomonic and 1531–1543 Adal campaign identities, source "
        "row, sides, and HCED tactical result reviewed."
    ),
    "canonical_event": _canonical_event(_source),
    "cohort": "solomonic_ethiopia_pre1855",
    "evidence_refs": ["loc_ethiopia_country_study", "met_ethiopian_christianity"],
    "raw_row": _source,
    "raw_row_sha256": _canonical_sha256(_source),
    "result": {"type": "win", "winner_side": 1},
    "side_1_entity_ids": ["adal_campaign_forces_1531"],
    "side_2_entity_ids": ["solomonic_ethiopian_empire_pre1855"],
}

WAVE7_GLOBAL_HCED_HOLDS: dict[str, dict[str, Any]] = {}
for _candidate_id, (_category, _reason, _evidence) in _HOLD_CONFIG.items():
    _source = _ROWS[_candidate_id]
    WAVE7_GLOBAL_HCED_HOLDS[_candidate_id] = {
        "canonical_event": _canonical_event(_source),
        "evidence_refs": list(_evidence),
        "hold_category": _category,
        "hold_reason": _reason,
        "raw_row": _source,
        "raw_row_sha256": _canonical_sha256(_source),
    }
WAVE7_GLOBAL_HCED_HOLDS["hced-Kadesh-1275-1"].update(
    {
        "canonical_event": {
            "canonical_key": "battle_of_kadesh:-1274:-1274",
            "date_precision": "year",
            "granularity": "engagement",
            "name": "Battle of Kadesh",
            "year_high": -1274,
            "year_low": -1274,
        },
        "duplicate_event_id": "battle_kadesh_1274_bce",
    }
)

WAVE7_GLOBAL_ORANGE_MIGRATIONS: dict[str, dict[str, Any]] = {}
for _event_id, _candidate_id in _MIGRATION_EVENT_CANDIDATES.items():
    _source = _ROWS[_candidate_id]
    WAVE7_GLOBAL_ORANGE_MIGRATIONS[_event_id] = {
        "candidate_id": _candidate_id,
        "event_id": _event_id,
        "evidence_refs": ["saho_orange_free_state", "uk_na_south_african_war"],
        "from_entity_id": "clio_q218023_1856_cfb4e08e",
        "migrated_event_sha256": _MIGRATION_FINAL_EVENT_SHA256[_event_id],
        "raw_row": _source,
        "raw_row_sha256": _canonical_sha256(_source),
        "source_event_sha256": _MIGRATION_SOURCE_EVENT_SHA256[_event_id],
        "to_entity_id": "orange_free_state_1854",
    }

# These fixtures are inserted separately to keep the audited source tuples legible.
WAVE7_GLOBAL_ENTITIES: tuple[dict[str, Any], ...] = (
    {
        "aliases": [],
        "continuity_note": (
            "Reviewed revolutionary-army label window from the May 1810 "
            "reorganization through the 1816 independence boundary. Later "
            "Argentine governments and civil-war factions receive no rating "
            "inheritance."
        ),
        "end_year": 1816,
        "id": "rio_de_la_plata_patriot_army_1810",
        "kind": "revolutionary_army",
        "name": "Patriot Army of the Río de la Plata (1810–1816)",
        "predecessors": [],
        "region": "South America",
        "source_ids": ["argentina_army_1810", "argentina_naval_independence"],
        "start_year": 1810,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Independent republic recognized in 1854 through the 1902 peace "
            "settlement. Its rating is rebuilt only from explicitly migrated and "
            "newly reviewed events; no rating is imported from a namesake or raw "
            "candidate."
        ),
        "end_year": 1902,
        "id": "orange_free_state_1854",
        "kind": "republic",
        "name": "Orange Free State",
        "predecessors": [],
        "region": "Southern Africa",
        "source_ids": ["saho_orange_free_state", "uk_na_south_african_war"],
        "start_year": 1854,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Dynasty 26 (Saite) identity only, through the Persian conquest in "
            "525 BCE. No rating crosses into earlier Egyptian kingdoms, Persian "
            "rule, or later Egyptian regimes."
        ),
        "end_year": -525,
        "id": "saite_egypt_664_bce",
        "kind": "dynastic_kingdom",
        "name": "Saite Egypt (Twenty-sixth Dynasty)",
        "predecessors": [],
        "region": "North Africa",
        "source_ids": ["met_saite_egypt"],
        "start_year": -664,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Ptolemaic dynastic kingdom from 305 to 30 BCE. No rating crosses "
            "into Macedonian administration, pharaonic predecessor periods, or "
            "Roman Egypt."
        ),
        "end_year": -30,
        "id": "ptolemaic_egypt_305_bce",
        "kind": "hellenistic_kingdom",
        "name": "Ptolemaic Kingdom of Egypt",
        "predecessors": [],
        "region": "North Africa",
        "source_ids": ["met_ptolemaic_egypt"],
        "start_year": -305,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Battle-specific Mamluk Egyptian force in 1798, not the medieval "
            "Mamluk Sultanate or a generic Egypt identity. No rating is inherited "
            "from either namesake."
        ),
        "end_year": 1798,
        "id": "mamluk_egyptian_forces_1798",
        "kind": "campaign_force",
        "name": "Mamluk Egyptian Forces (1798)",
        "predecessors": [],
        "region": "North Africa",
        "source_ids": ["met_battle_pyramids"],
        "start_year": 1798,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Reviewed generic-label window for the independent Kingdom of Egypt "
            "through the 1952 revolution boundary. No rating crosses into the "
            "1953 republic or adjacent regimes."
        ),
        "end_year": 1952,
        "id": "kingdom_egypt_1922",
        "kind": "kingdom",
        "name": "Kingdom of Egypt",
        "predecessors": [],
        "region": "North Africa",
        "source_ids": ["egypt_sis_modern_era"],
        "start_year": 1922,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Solomonic imperial identity beginning with Yekuno Amlak in 1270 and "
            "ending before Tewodros II's 1855 restoration. No rating extends into "
            "the existing post-1855 Ethiopian Empire seed."
        ),
        "end_year": 1854,
        "id": "solomonic_ethiopian_empire_pre1855",
        "kind": "empire",
        "name": "Solomonic Ethiopian Empire (pre-1855)",
        "predecessors": [],
        "region": "Northeast Africa",
        "source_ids": ["loc_ethiopia_country_study", "met_ethiopian_christianity"],
        "start_year": 1270,
    },
    {
        "aliases": [],
        "continuity_note": (
            "Campaign-bounded Adal forces for the 1531–1543 invasion period "
            "identified by the reviewed source. No rating is inherited from a "
            "broader or namesake Adal polity."
        ),
        "end_year": 1543,
        "id": "adal_campaign_forces_1531",
        "kind": "state_campaign_army",
        "name": "Adal Campaign Forces (1531–1543)",
        "predecessors": [],
        "region": "Horn of Africa",
        "source_ids": ["met_ethiopian_christianity"],
        "start_year": 1531,
    },
)
WAVE7_GLOBAL_SOURCES: tuple[dict[str, Any], ...] = (
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "argentina_army_1810",
        "license": "Citation and link only",
        "publisher": "Government of Argentina",
        "source_family_id": "argentina_gob_ar",
        "source_type": "official_or_academic_reference",
        "title": "215th anniversary of the Argentine Army",
        "url": (
            "https://www.argentina.gob.ar/noticias/"
            "215deg-aniversario-del-ejercito-argentino"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "argentina_naval_independence",
        "license": "Citation and link only",
        "publisher": "Argentine Navy, Government of Argentina",
        "source_family_id": "argentina_gob_ar",
        "source_type": "official_or_academic_reference",
        "title": "The War of Independence, 1810–1824",
        "url": (
            "https://www.argentina.gob.ar/armada/nueva-historia-naval/"
            "independencia-1810"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "saho_orange_free_state",
        "license": "Citation and link only",
        "publisher": "South African History Online",
        "source_family_id": "south_african_history_online",
        "source_type": "official_or_academic_reference",
        "title": "Adoption of the Orange Free State constitution",
        "url": (
            "https://sahistory.org.za/dated-event/"
            "adoption-orange-free-state-constitution"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "uk_na_south_african_war",
        "license": "Citation and link only",
        "publisher": "The National Archives (United Kingdom)",
        "source_family_id": "uk_national_archives",
        "source_type": "official_or_academic_reference",
        "title": "The South African War, 1899–1902",
        "url": (
            "https://www.nationalarchives.gov.uk/education/resources/"
            "the-south-african-war-how-did-the-british-conduct-war-in-1899-1902/"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_saite_egypt",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "Egypt in the Late Period (ca. 664–332 B.C.)",
        "url": (
            "https://www.metmuseum.org/essays/egypt-in-the-late-period-ca-712-332-b-c"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_ptolemaic_egypt",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "Egypt in the Ptolemaic Period",
        "url": "https://www.metmuseum.org/essays/egypt-in-the-ptolemaic-period",
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_fatimid_period",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "The Art of the Fatimid Period (909–1171)",
        "url": (
            "https://www.metmuseum.org/essays/the-art-of-the-fatimid-period-909-1171"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_ayyubid_period",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "The Art of the Ayyubid Period (ca. 1171–1260)",
        "url": (
            "https://www.metmuseum.org/essays/"
            "the-art-of-the-ayyubid-period-ca-1171-1260"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_mamluk_period",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "The Art of the Mamluk Period (1250–1517)",
        "url": (
            "https://www.metmuseum.org/essays/the-art-of-the-mamluk-period-1250-1517"
        ),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_battle_pyramids",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_collection",
        "source_type": "official_or_academic_reference",
        "title": "Battle of the Pyramids, July 21, 1798",
        "url": "https://www.metmuseum.org/art/collection/search/339816",
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "egypt_sis_modern_era",
        "license": "Citation and link only",
        "publisher": "Egypt State Information Service",
        "source_family_id": "egypt_state_information_service",
        "source_type": "official_or_academic_reference",
        "title": "Modern Era",
        "url": "https://sis.gov.eg/en/egypt/history/egypts-history/modern-era/",
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "met_ethiopian_christianity",
        "license": "Citation and link only",
        "publisher": "The Metropolitan Museum of Art",
        "source_family_id": "met_heilbrunn_timeline",
        "source_type": "official_or_academic_reference",
        "title": "African Christianity in Ethiopia",
        "url": ("https://www.metmuseum.org/essays/african-christianity-in-ethiopia"),
    },
    {
        "accessed": "2026-07-16",
        "evidence_roles": ["identity_boundary_or_context_reference"],
        "id": "loc_ethiopia_country_study",
        "license": "Citation and link only",
        "publisher": "Library of Congress",
        "source_family_id": "library_of_congress_country_studies",
        "source_type": "official_or_academic_reference",
        "title": "Ethiopia: A Country Study",
        "url": (
            "https://tile.loc.gov/storage-services/master/frd/frdcstdy/et/"
            "ethiopiacountrys00ofca_0/ethiopiacountrys00ofca_0.pdf"
        ),
    },
)
WAVE7_GLOBAL_SUPERSESSIONS: dict[str, dict[str, Any]] = {
    "cliopatria-613": {
        "boundary_note": "The 1272?1935 raw envelope is split at the project's reviewed "
        "1855 reset; the pre-1855 and post-1855 entities never inherit one "
        "another's rating.",
        "raw_candidate": {
            "candidate_id": "cliopatria-613",
            "canonical_name_candidate": "Ethiopian Empire",
            "end_year": 1935,
            "identity_basis": "wikidata_name",
            "interval_segments": [
                {"end_year": 1284, "start_year": 1272},
                {"end_year": 1332, "start_year": 1285},
                {"end_year": 1414, "start_year": 1333},
                {"end_year": 1501, "start_year": 1415},
                {"end_year": 1528, "start_year": 1502},
                {"end_year": 1533, "start_year": 1529},
                {"end_year": 1539, "start_year": 1534},
                {"end_year": 1546, "start_year": 1540},
                {"end_year": 1563, "start_year": 1547},
                {"end_year": 1578, "start_year": 1564},
                {"end_year": 1635, "start_year": 1579},
                {"end_year": 1768, "start_year": 1636},
                {"end_year": 1889, "start_year": 1769},
                {"end_year": 1894, "start_year": 1890},
                {"end_year": 1897, "start_year": 1895},
                {"end_year": 1899, "start_year": 1898},
                {"end_year": 1904, "start_year": 1900},
                {"end_year": 1907, "start_year": 1905},
                {"end_year": 1931, "start_year": 1908},
                {"end_year": 1935, "start_year": 1932},
            ],
            "record_type": "POLITY",
            "seshat_ids": ["et_ethiopian_k"],
            "source": "cliopatria-0.2.0",
            "source_snapshot": "data/raw/cliopatria-0.2.0/20260713T164025Z-d01ae3a20d35.zip",
            "start_year": 1272,
            "temporal_coverage_groups": [{"end_year": 1935, "start_year": 1272}],
            "wikidata_ids": ["Q207521"],
            "wikipedia_titles": ["Ethiopian Empire"],
        },
        "raw_candidate_sha256": "42de39e1a7ba3a9252fcfd8cdd0af1f98ff59b5395dbf580122d506043e4c396",
        "replacement_entity_ids": [
            "solomonic_ethiopian_empire_pre1855",
            "ethiopian_empire",
        ],
        "source_entity_id": "clio_et_ethiopian_k_1272_654cac97",
    },
    "cliopatria-661": {
        "boundary_note": "The raw 1856?1899 candidate is superseded by the reviewed "
        "1854?1902 republic; only the five enumerated event migrations "
        "move existing history.",
        "raw_candidate": {
            "candidate_id": "cliopatria-661",
            "canonical_name_candidate": "Free Orange State",
            "end_year": 1899,
            "identity_basis": "wikidata_name",
            "interval_segments": [
                {"end_year": 1870, "start_year": 1856},
                {"end_year": 1884, "start_year": 1871},
                {"end_year": 1897, "start_year": 1885},
                {"end_year": 1899, "start_year": 1898},
            ],
            "record_type": "POLITY",
            "seshat_ids": [],
            "source": "cliopatria-0.2.0",
            "source_snapshot": "data/raw/cliopatria-0.2.0/20260713T164025Z-d01ae3a20d35.zip",
            "start_year": 1856,
            "temporal_coverage_groups": [{"end_year": 1899, "start_year": 1856}],
            "wikidata_ids": ["Q218023"],
            "wikipedia_titles": ["Orange Free State"],
        },
        "raw_candidate_sha256": "ed680e4fd0a82628b5f6fd17df2b3325c4ebccbb5da1e44f9b12e038d8dc97b5",
        "replacement_entity_ids": ["orange_free_state_1854"],
        "source_entity_id": "clio_q218023_1856_cfb4e08e",
    },
}
