"""Frozen Wave 7 Central/East identity, evidence, promotion, and hold data."""

from __future__ import annotations

from typing import Any


def _source(
    source_id: str,
    publisher: str,
    title: str,
    url: str,
) -> dict[str, Any]:
    return {
        "id": source_id,
        "title": title,
        "url": url,
        "publisher": publisher,
        "license": "Citation and link only",
        "source_type": "official_or_academic_reference",
        "accessed": "2026-07-16",
        "source_family_id": f"wave7_central_{source_id}",
        "evidence_roles": ["identity_boundary_or_context_reference"],
    }


WAVE7_CENTRAL_SOURCES = [
    _source(
        "wave7_poland_bar_archive",
        "National Archives in Krakow",
        "Bar Confederation forces and 1768-1772 chronology",
        "https://ank.gov.pl/konfederacja/index.html",
    ),
    _source(
        "wave7_poland_1792_agad",
        "Central Archives of Historical Records in Warsaw",
        "Commonwealth army and Russian war of 1792",
        "https://agad.gov.pl/230K3M/WAR_gb.html",
    ),
    _source(
        "wave7_poland_kosciuszko_museum",
        "Polish Army Museum in Warsaw",
        "Kosciuszko Uprising forces in 1794",
        "https://muzeumwp.pl/en/2024/05/08/photo-report-from-the-historical-picnic-on-the-occasion-of-the-104th-anniversary-of-the-polish-army-museum-and-the-230th-anniversary-of-the-kosciuszko-uprising/",
    ),
    _source(
        "wave7_poland_november_archive",
        "State Archives in Lublin",
        "November Uprising chronology, 1830-1831",
        "https://lublin.ap.gov.pl/popularyzacja/galerie-online/powstanie-listopadowe-1830-1831/",
    ),
    _source(
        "wave7_poland_warsaw_ushmm",
        "United States Holocaust Memorial Museum",
        "Polish Home Army and Warsaw Uprising result in 1944",
        "https://encyclopedia.ushmm.org/content/en/article/the-warsaw-polish-uprising",
    ),
    _source(
        "wave7_serbia_medieval_museum",
        "Historical Museum of Serbia",
        "Nemanjić state, kingdom, and imperial identity context",
        "https://imus.org.rs/en/exhibitions/kings-and-saints-of-serbia/",
    ),
    _source(
        "wave7_serbia_uprisings_museum",
        "Historical Museum of Serbia",
        "First and Second Serbian Uprisings and restoration of statehood",
        "https://imus.org.rs/en/about-us/",
    ),
    _source(
        "wave7_serbia_modern_government",
        "Government of Serbia",
        "Modern Serbia, principality, and 1882 kingdom transition",
        "https://www.arhiva.serbia.gov.rs/enc/history/modern.html",
    ),
    _source(
        "wave7_serbian_krajina_irmct",
        "International Residual Mechanism for Criminal Tribunals",
        "Operation Storm, Knin, and the Krajina Serb belligerent",
        "https://www.irmct.org/en/mip/features/storm",
    ),
    _source(
        "wave7_artemisium_perseus",
        "Perseus Digital Library, Tufts University",
        "Greek allied fleet and doubtful result at Artemisium",
        "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126%3Abook%3D8",
    ),
    _source(
        "wave7_greek_revolution_parliament",
        "Hellenic Parliament",
        "Revolutionary governments and military organization from 1821",
        "https://www.hellenicparliament.gr/en/Vouli-ton-Ellinon/To-Politevma/Syntagmatiki-Istoria/",
    ),
    _source(
        "wave7_greece_restored_presidency",
        "Presidency of the Hellenic Republic",
        "Restored Greek monarchy from 1935 through 1967",
        "https://www.presidency.gr/en/mansion/history/",
    ),
    _source(
        "wave7_iran_pahlavi_loc",
        "Library of Congress",
        "Pahlavi dynasty boundary, 1925-1979",
        "https://www.loc.gov/aba/publications/Archived-LCC2017/DS-DX-text.pdf",
    ),
]


def _entity(
    entity_id: str,
    name: str,
    kind: str,
    start_year: int,
    end_year: int,
    region: str,
    source_ids: tuple[str, ...],
) -> dict[str, Any]:
    return {
        "id": entity_id,
        "name": name,
        "kind": kind,
        "start_year": start_year,
        "end_year": end_year,
        "region": region,
        "aliases": [],
        "predecessors": [],
        "continuity_note": (
            "Exact Wave 7 Central/East reviewed-party boundary. It opens no broad "
            "alias, country-label, or cross-era fallback, and no predecessor or "
            "successor rating is inherited."
        ),
        "source_ids": list(source_ids),
    }


WAVE7_CENTRAL_ENTITIES = [
    _entity(
        "bar_confederation_forces",
        "Bar Confederation Forces",
        "confederate_forces",
        1768,
        1772,
        "Eastern Europe",
        ("wave7_poland_bar_archive",),
    ),
    _entity(
        "polish_lithuanian_commonwealth_army_1792",
        "Polish-Lithuanian Commonwealth Army (1792)",
        "state_armed_forces",
        1792,
        1792,
        "Eastern Europe",
        ("wave7_poland_1792_agad",),
    ),
    _entity(
        "kosciuszko_uprising_forces",
        "Kosciuszko Uprising Forces",
        "revolutionary_forces",
        1794,
        1794,
        "Eastern Europe",
        ("wave7_poland_kosciuszko_museum",),
    ),
    _entity(
        "november_uprising_polish_forces",
        "Polish Forces of the November Uprising",
        "revolutionary_government_forces",
        1830,
        1831,
        "Eastern Europe",
        ("wave7_poland_november_archive",),
    ),
    _entity(
        "warsaw_uprising_polish_forces_1944",
        "Polish Warsaw Uprising Forces",
        "resistance_forces",
        1944,
        1944,
        "Eastern Europe",
        ("wave7_poland_warsaw_ushmm",),
    ),
    _entity(
        "serbian_grand_principality_nemanjic",
        "Serbian Grand Principality under the Nemanjić Dynasty",
        "grand_principality",
        1166,
        1217,
        "Southeastern Europe",
        ("wave7_serbia_medieval_museum",),
    ),
    _entity(
        "kingdom_serbia_medieval",
        "Medieval Kingdom of Serbia",
        "kingdom",
        1217,
        1346,
        "Southeastern Europe",
        ("wave7_serbia_medieval_museum",),
    ),
    _entity(
        "serbian_empire_medieval",
        "Serbian Empire",
        "empire",
        1346,
        1371,
        "Southeastern Europe",
        ("wave7_serbia_medieval_museum",),
    ),
    _entity(
        "serbian_despotate",
        "Serbian Despotate",
        "despotate",
        1402,
        1459,
        "Southeastern Europe",
        ("wave7_serbia_medieval_museum",),
    ),
    _entity(
        "serbian_revolutionary_forces_1804_1815",
        "Serbian Revolutionary Forces (1804-1815)",
        "revolutionary_forces",
        1804,
        1815,
        "Southeastern Europe",
        ("wave7_serbia_uprisings_museum",),
    ),
    _entity(
        "principality_serbia_1815",
        "Principality of Serbia",
        "principality",
        1815,
        1882,
        "Southeastern Europe",
        ("wave7_serbia_modern_government",),
    ),
    _entity(
        "republic_serbian_krajina_forces",
        "Republic of Serbian Krajina Forces",
        "de_facto_state_forces",
        1991,
        1995,
        "Southeastern Europe",
        ("wave7_serbian_krajina_irmct",),
    ),
    _entity(
        "hellenic_coalition_artemisium_480_bce",
        "Hellenic Coalition Fleet at Artemisium",
        "military_coalition",
        -480,
        -480,
        "Eastern Mediterranean",
        ("wave7_artemisium_perseus",),
    ),
    _entity(
        "kingdom_greece_restored",
        "Restored Kingdom of Greece",
        "kingdom",
        1935,
        1967,
        "Southern Europe",
        ("wave7_greece_restored_presidency",),
    ),
    _entity(
        "imperial_state_iran_pahlavi",
        "Imperial State of Iran under the Pahlavi Dynasty",
        "monarchy",
        1925,
        1979,
        "West Asia",
        ("wave7_iran_pahlavi_loc",),
    ),
]


def _promotion(
    candidate_id: str,
    raw_row_sha256: str,
    source_row: int,
    name: str,
    year: int,
    side_1_raw: str,
    side_2_raw: str,
    winner_raw: str,
    loser_raw: str | None,
    side_1_entity_ids: tuple[str, ...],
    side_2_entity_ids: tuple[str, ...],
    cohort: str,
    evidence_refs: tuple[str, ...],
    audit_note: str,
) -> dict[str, Any]:
    if winner_raw == "Draw":
        result = {"type": "draw"}
    elif winner_raw == side_1_raw:
        result = {"type": "win", "winner_side": 1}
    elif winner_raw == side_2_raw:
        result = {"type": "win", "winner_side": 2}
    else:
        raise ValueError(f"Unaligned frozen result for {candidate_id}")
    return {
        "candidate_id": candidate_id,
        "raw_row_sha256": raw_row_sha256,
        "raw_contract": {
            "candidate_id": candidate_id,
            "source_row": source_row,
            "name": name,
            "year_low": year,
            "year_high": year,
            "side_1_raw": side_1_raw,
            "side_2_raw": side_2_raw,
            "winner_raw": winner_raw,
            "loser_raw": loser_raw,
        },
        "side_1_entity_ids": side_1_entity_ids,
        "side_2_entity_ids": side_2_entity_ids,
        "result": result,
        "cohort": cohort,
        "evidence_refs": evidence_refs,
        "audit_note": audit_note,
        "canonical_event": {
            "name": name,
            "year_low": year,
            "year_high": year,
            "date_precision": "year",
            "granularity": "engagement",
            "canonical_key": f"wave7-central:{candidate_id}",
        },
    }


_POLAND_BAR = ("wave7_poland_bar_archive",)
_POLAND_1792 = ("wave7_poland_1792_agad",)
_POLAND_1794 = ("wave7_poland_kosciuszko_museum",)
_POLAND_1831 = ("wave7_poland_november_archive",)
_POLAND_1944 = ("wave7_poland_warsaw_ushmm",)
_SERBIA_MEDIEVAL = ("wave7_serbia_medieval_museum",)
_SERBIA_UPRISING = ("wave7_serbia_uprisings_museum",)
_SERBIA_PRINCIPALITY = ("wave7_serbia_modern_government",)
_SERBIA_KRAJINA = ("wave7_serbian_krajina_irmct",)
_GREECE_ARTEMISIUM = ("wave7_artemisium_perseus",)
_GREECE_REVOLUTION = ("wave7_greek_revolution_parliament",)
_GREECE_RESTORED = ("wave7_greece_restored_presidency",)
_IRAN_PAHLAVI = ("wave7_iran_pahlavi_loc",)


WAVE7_CENTRAL_PROMOTION_CONTRACTS = {
    row["candidate_id"]: row
    for row in [
        _promotion(
            "hced-Orekhovo1769-1",
            "81c73045223a1c3dc7a2d19d5ad4dae83a5126ce4332c136bc1320c5a5b6dd3f",
            11873,
            "Orekhovo",
            1769,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("bar_confederation_forces",),
            "poland_bar_confederation",
            _POLAND_BAR,
            "The generic rebel label is confined to the Bar Confederation for this row.",
        ),
        _promotion(
            "hced-Lanskroun1771-1",
            "c3bef8bb0a2d0905c1cd81662daa02a9d32bada289f2f7d3db4f158e506fff17",
            8947,
            "Lanskroun",
            1771,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("bar_confederation_forces",),
            "poland_bar_confederation",
            _POLAND_BAR,
            "The generic rebel label is confined to the Bar Confederation for this row.",
        ),
        _promotion(
            "hced-Stalowicz1771-1",
            "d8505948106e757d3ccedf1926d10ef2a6448d2f34b2f019debf1e00a9fd2ea4",
            15167,
            "Stalowicz",
            1771,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("bar_confederation_forces",),
            "poland_bar_confederation",
            _POLAND_BAR,
            "The generic rebel label is confined to the Bar Confederation for this row.",
        ),
        _promotion(
            "hced-Zielenice1792-1",
            "ad9a06a795f19aed8ffedc17c0a3eefc29bc87d8bd8d03e44e0ee87c695c66e7",
            17689,
            "Zielenice",
            1792,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("polish_lithuanian_commonwealth_army_1792",),
            ("russian_empire",),
            "poland_commonwealth_1792",
            _POLAND_1792,
            "Candidate-specific correction: the raw rebel label denotes the Commonwealth army, not a cross-uprising rebel identity.",
        ),
        _promotion(
            "hced-Bydgoszcz1794-1",
            "2e224baaace0f1f804bfdf9fc93627009f06a4c1c5d189fd00fc2e72d09cf54f",
            2801,
            "Bydgoszcz",
            1794,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("kosciuszko_uprising_forces",),
            ("russian_empire",),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising.",
        ),
        _promotion(
            "hced-Maciejowice1794-1",
            "7e27dddb824cd4f27baf1d5fc6287fe1b2dd249353abf2194cdcbfc54b7be45b",
            9643,
            "Maciejowice",
            1794,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("kosciuszko_uprising_forces",),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising.",
        ),
        _promotion(
            "hced-Raclawice1794-1",
            "30b85e0a6b3544cd7118000acccbda8a2cc0fd023e236ebdb3c7a7f3dd2b02a4",
            13099,
            "Raclawice",
            1794,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("kosciuszko_uprising_forces",),
            ("russian_empire",),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising.",
        ),
        _promotion(
            "hced-Szczekociny1794-1",
            "4ad6c280fbf79a5cbf364aa1937b65850b9b07fa04b5a40d73212d8759a7e202",
            15443,
            "Szczekociny",
            1794,
            "Prussia",
            "Polish Rebels",
            "Prussia",
            "Polish Rebels",
            ("kingdom_prussia",),
            ("kosciuszko_uprising_forces",),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising.",
        ),
        _promotion(
            "hced-Terespol1794-1",
            "efbea35c90d86bab8b85d3b90548e1f2932412fd9b07a871f8c19fc0d561ec75",
            15801,
            "Terespol",
            1794,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("kosciuszko_uprising_forces",),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising.",
        ),
        _promotion(
            "hced-Warsaw (1st)1794-1",
            "361e7e40bfe2f380b6935a3944bf9e77021e0be802f1159cc95956b7423796d0",
            17119,
            "Warsaw (1st)",
            1794,
            "Polish Rebels",
            "Russia, Prussia",
            "Polish Rebels",
            "Russia, Prussia",
            ("kosciuszko_uprising_forces",),
            ("russian_empire", "kingdom_prussia"),
            "poland_kosciuszko_1794",
            _POLAND_1794,
            "The raw rebel label is limited to the 1794 Kosciuszko Uprising; the opposing coalition remains explicit.",
        ),
        _promotion(
            "hced-Grochow1831-1",
            "e3fcbc5e85ff3f743732a0c04b5b06c0ab00907425ae83bbd952cf7472808fc6",
            6439,
            "Grochow",
            1831,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("november_uprising_polish_forces",),
            ("russian_empire",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Ostrolenka1831-1",
            "1c10ca4c5ced7c510aed56e193c33c48cf9d5235a0a2f758f0c2d011eb4f5b68",
            11951,
            "Ostrolenka",
            1831,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("november_uprising_polish_forces",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Praga1831-1",
            "79aa2ce34ac0dfbf105d382ffc35bbe5e3a5aa9b38b81d4d69a6ff04d604f7cc",
            12835,
            "Praga",
            1831,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("november_uprising_polish_forces",),
            ("russian_empire",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Siedlce1831-1",
            "018fc0a46ad12a73c78a131bbdb425d9f53ea45008f1b5a8111315a4db6d65cc",
            14767,
            "Siedlce",
            1831,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("november_uprising_polish_forces",),
            ("russian_empire",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Stoczek1831-1",
            "f8ed50ea13f2647157aec271628be21c76f6604b6f22c719dbddb948c3862456",
            15227,
            "Stoczek",
            1831,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("november_uprising_polish_forces",),
            ("russian_empire",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Warsaw1831-1",
            "22f5eb960a88156beb5c016fe33c7a5f963e5af21f49abaed38071ced47ca2e3",
            17121,
            "Warsaw",
            1831,
            "Russia",
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            ("russian_empire",),
            ("november_uprising_polish_forces",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Wawer1831-1",
            "1a44f348a0e970dc2b0cebedb7c2db59bdb430cb8ab85e742038603e3412da86",
            17161,
            "Wawer",
            1831,
            "Polish Rebels",
            "Russia",
            "Polish Rebels",
            "Russia",
            ("november_uprising_polish_forces",),
            ("russian_empire",),
            "poland_november_uprising",
            _POLAND_1831,
            "The raw rebel label is limited to the November Uprising.",
        ),
        _promotion(
            "hced-Warsaw1944-1",
            "67a3a687e0201393c7552675db92adc391d6311c7925d514ab04ea9d4efb8cea",
            17133,
            "Warsaw",
            1944,
            "Germany",
            "Polish Rebels",
            "Germany",
            "Polish Rebels",
            ("nazi_germany",),
            ("warsaw_uprising_polish_forces_1944",),
            "poland_warsaw_uprising",
            _POLAND_1944,
            "Candidate-specific correction: the raw rebel label denotes Warsaw Uprising resistance forces.",
        ),
        _promotion(
            "hced-Morava1190-1",
            "a60071a6826f88197575033752d25415ed4a114cf92a3796750fd781ba1cf1f1",
            10791,
            "Morava",
            1190,
            "Byzantium",
            "Serbia",
            "Byzantium",
            "Serbia",
            ("byzantine_empire",),
            ("serbian_grand_principality_nemanjic",),
            "serbia_grand_principality",
            _SERBIA_MEDIEVAL,
            "Serbia is resolved to the Nemanjić grand principality, not a modern state.",
        ),
        _promotion(
            "hced-Stefaniana1344-1",
            "73291203c6eeedc0ed81b43cebeac43c443858867d60e11de57018633d929e0a",
            15201,
            "Stefaniana",
            1344,
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            ("kingdom_serbia_medieval",),
            ("ottoman_empire",),
            "serbia_medieval_kingdom",
            _SERBIA_MEDIEVAL,
            "Serbia is resolved to the medieval kingdom before the imperial transition.",
        ),
        _promotion(
            "hced-Adrianople1355-1",
            "4928af1f17b056b534f8719074761b429d5f5cf6cbd1863eec8ce9c5e7b2c84e",
            181,
            "Adrianople",
            1355,
            "Serbia",
            "Byzantium",
            "Serbia",
            "Byzantium",
            ("serbian_empire_medieval",),
            ("byzantine_empire",),
            "serbia_empire",
            _SERBIA_MEDIEVAL,
            "Serbia is resolved to the medieval empire.",
        ),
        _promotion(
            "hced-Maritza1371-1",
            "2c04971874fdb9e3f2072b5a08972a8971b5be00ec9ffb69828b3b34ac058bb3",
            10015,
            "Maritza",
            1371,
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            ("ottoman_empire",),
            ("serbian_empire_medieval",),
            "serbia_empire",
            _SERBIA_MEDIEVAL,
            "The exact 1371 row remains attached to the Serbian imperial belligerent; later fragmentation is not bridged.",
        ),
        _promotion(
            "hced-Semendria1439-1",
            "c3fb66ce9c9eb69d3ffae790ca3b3d320dd064ec679739c8f7018830aafcee20",
            14513,
            "Semendria",
            1439,
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            ("ottoman_empire",),
            ("serbian_despotate",),
            "serbia_despotate",
            _SERBIA_MEDIEVAL,
            "Serbia is resolved to the Serbian Despotate.",
        ),
        _promotion(
            "hced-Misar1806-1",
            "bd26e7092a0f26794957a760f0697dbd5c64e8b17c8d15c3337a9377202b5671",
            10531,
            "Misar",
            1806,
            "Serbia",
            "Turkey",
            "Serbia",
            "Turkey",
            ("serbian_revolutionary_forces_1804_1815",),
            ("ottoman_empire",),
            "serbia_revolutionary",
            _SERBIA_UPRISING,
            "Serbia denotes First Uprising forces; the raw Turkey label is the Ottoman belligerent for this exact row.",
        ),
        _promotion(
            "hced-Varvarin1810-1",
            "c5d4cf917ae4d31bd08eca4ea7a7054957ebab1f2ea2494030b0232edcb651bd",
            16657,
            "Varvarin",
            1810,
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            ("serbian_revolutionary_forces_1804_1815",),
            ("ottoman_empire",),
            "serbia_revolutionary",
            _SERBIA_UPRISING,
            "Serbia denotes First Uprising forces, not the later principality.",
        ),
        _promotion(
            "hced-Belgrade1862-1",
            "8dc94040534af2e8d3ca968742b18a866259884f576f71ba5992fd2f19a2a40f",
            1989,
            "Belgrade",
            1862,
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            ("ottoman_empire",),
            ("principality_serbia_1815",),
            "serbia_principality",
            _SERBIA_PRINCIPALITY,
            "Serbia denotes the Principality of Serbia.",
        ),
        _promotion(
            "hced-Alexinatz1876-1",
            "b978abb435a5afbbef77270f5543f0415be1a791f083175dca0e63bbeab29361",
            473,
            "Alexinatz",
            1876,
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            ("ottoman_empire",),
            ("principality_serbia_1815",),
            "serbia_principality",
            _SERBIA_PRINCIPALITY,
            "Serbia denotes the Principality of Serbia.",
        ),
        _promotion(
            "hced-Djunis1876-1",
            "2ea006b57fc0cdc1412578d303477ae4ad01a9887d23f714ed9afb0b7fc64636",
            4777,
            "Djunis",
            1876,
            "Ottoman Empire",
            "Serbia",
            "Ottoman Empire",
            "Serbia",
            ("ottoman_empire",),
            ("principality_serbia_1815",),
            "serbia_principality",
            _SERBIA_PRINCIPALITY,
            "Serbia denotes the Principality of Serbia.",
        ),
        _promotion(
            "hced-Knin1995-1",
            "f4d4c6f38abf620dd45e9b7fdf7712fdcd7b1b3c984efd9606bf8577b77b330e",
            8445,
            "Knin",
            1995,
            "Croatia",
            "Serbia",
            "Croatia",
            "Serbia",
            ("clio_q224_1992_4605be1c",),
            ("republic_serbian_krajina_forces",),
            "serbian_krajina_knin",
            _SERBIA_KRAJINA,
            "Candidate-specific correction: Serbia denotes the Republic of Serbian Krajina forces at Knin, not Serbia or Yugoslavia.",
        ),
        _promotion(
            "hced-Artemisium-480-1",
            "dfb5d8b47fb74fac66f2785d6c2ffb322dcc881613ff7565b5ceb0f5a39d1fb9",
            1143,
            "Artemisium",
            -480,
            "Greece",
            "Persia",
            "Draw",
            None,
            ("hellenic_coalition_artemisium_480_bce",),
            ("achaemenid_empire",),
            "greece_artemisium",
            _GREECE_ARTEMISIUM,
            "Candidate-specific correction: Greece denotes the enumerated Hellenic allied fleet; no later Greek polity inherits this result.",
        ),
        _promotion(
            "hced-Anatoliko1823-1",
            "f706a19a4df3eeb1a369c47668ff3909f71e812d018791371d04dd60dc6b55d2",
            767,
            "Anatoliko",
            1823,
            "Turkey",
            "Greece",
            "Turkey",
            "Greece",
            ("ottoman_empire",),
            ("greek_revolutionaries_1821",),
            "greece_revolutionary",
            _GREECE_REVOLUTION,
            "Greece denotes the existing Greek revolutionary identity; the raw Turkey label is the Ottoman belligerent for this exact row.",
        ),
        _promotion(
            "hced-Greece1940-1",
            "83581ec7320383725a8649d57f72797dad720d2c39de460c392765be441b2827",
            6413,
            "Greece",
            1940,
            "Greece",
            "Italy",
            "Greece",
            "Italy",
            ("kingdom_greece_restored",),
            ("clio_it_italian_k_587_7218f0c7",),
            "greece_restored_kingdom",
            _GREECE_RESTORED,
            "Greece denotes the restored kingdom, with no continuity through the 1967 regime break.",
        ),
        _promotion(
            "hced-Iran1941-1",
            "bc52a0cbe1ffe3262540c56c5e493c8b78bb53f76250784d0e8ba15e8af496ff",
            7431,
            "Iran",
            1941,
            "United Kingdom, USSR",
            "Iran",
            "United Kingdom, USSR",
            "Iran",
            ("united_kingdom", "soviet_union"),
            ("imperial_state_iran_pahlavi",),
            "iran_pahlavi",
            _IRAN_PAHLAVI,
            "Iran denotes the Pahlavi Imperial State; the 1979 successor boundary remains closed.",
        ),
    ]
}


def _hold(
    candidate_id: str,
    raw_row_sha256: str,
    source_row: int,
    name: str,
    year: int,
    side_1_raw: str,
    side_2_raw: str,
    winner_raw: str,
    loser_raw: str,
    cohort: str,
    reason: str,
) -> dict[str, Any]:
    return {
        "candidate_id": candidate_id,
        "raw_row_sha256": raw_row_sha256,
        "raw_contract": {
            "candidate_id": candidate_id,
            "source_row": source_row,
            "name": name,
            "year_low": year,
            "year_high": year,
            "side_1_raw": side_1_raw,
            "side_2_raw": side_2_raw,
            "winner_raw": winner_raw,
            "loser_raw": loser_raw,
        },
        "cohort": cohort,
        "reason": reason,
    }


WAVE7_CENTRAL_HOLDS = {
    row["candidate_id"]: row
    for row in [
        _hold(
            "hced-Velbuzhde1330-1",
            "7912a811d524ad2929456f47bdf0010b557d2ace755519ff5f23b98cddcce662",
            16693,
            "Velbuzhde",
            1330,
            "Serbia",
            "Bulgaria",
            "Serbia",
            "Bulgaria",
            "serbia_medieval_kingdom",
            "The Serbian kingdom is resolved, but the Bulgaria opponent remains unresolved in this lane.",
        ),
        _hold(
            "hced-Kossovo1999-1",
            "af89e026af4195fc02445447bfa8812963d85ada6a4509e646b4efc30b8de15c",
            8569,
            "Kossovo",
            1999,
            "NATO, Kosovar Albanian Rebels",
            "Serbia",
            "NATO, Kosovar Albanian Rebels",
            "Serbia",
            "serbia_kosovo_1999",
            "The row combines NATO and Kosovar Albanian rebels and mislabels the Federal Republic of Yugoslavia as Serbia; no safe two-side contract is inferred.",
        ),
        _hold(
            "hced-Florina1947-1",
            "e167f31c76122b8c245f438b633df79a402c4f63a2235990f3ac9ccfc993ff1b",
            5575,
            "Florina",
            1947,
            "Greece",
            "Greek Communists",
            "Greece",
            "Greek Communists",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Florina1949-1",
            "bca7bf6da666d2091d02d2ad66e2710012afa2b9774a0cb44a17814a0afd8d88",
            5577,
            "Florina",
            1949,
            "Greece",
            "Greek Communists",
            "Greece",
            "Greek Communists",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Karpenision1949-1",
            "a925a98271af56442d9b4e58cf58fe2f516d2926f7ce54f46f2c187a872847be",
            8063,
            "Karpenision",
            1949,
            "Greece",
            "Greek Communist Rebels",
            "Greece",
            "Greek Communist Rebels",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Kastoria1948-1",
            "523076f5e8e46f7c0dca35c2201063c883601676cd12a745a05de22cd6441860",
            8107,
            "Kastoria",
            1948,
            "Greece",
            "Greek Communist Rebels",
            "Greece",
            "Greek Communist Rebels",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Litokhoro1946-1",
            "9c91da29fab49538c0cc2d853cb90b1e01461037a812a46a23a63f888a0f7002",
            9307,
            "Litokhoro",
            1946,
            "Greek Communist Rebels",
            "Greece",
            "Greek Communist Rebels",
            "Greece",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Roumeli1948-1",
            "9aa33f00dfb7a7a18e6c4b6c063265f5f34dbed78f8cfeff3058e9466b8a808e",
            13599,
            "Roumeli",
            1948,
            "Greece",
            "Greek Communists",
            "Greece",
            "Greek Communists",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
        _hold(
            "hced-Vitsi1949-1",
            "a76c5a483bf8565dfddb7b1ffdf7983f36c70652d468180c941d54a1b9d810f6",
            16953,
            "Vitsi",
            1949,
            "Greece",
            "Greek Communists",
            "Greece",
            "Greek Communists",
            "greece_civil_war",
            "The restored kingdom is resolved, but the generic communist actor requires its own evidence-backed identity.",
        ),
    ]
}


# Generic policies deliberately exclude transition years. Candidate-specific contracts
# above may bind an exact reviewed row at an endpoint without opening a broad fallback.
WAVE7_CENTRAL_LABEL_WINDOWS: dict[str, tuple[tuple[int, int, tuple[str, ...]], ...]] = {
    "polish rebels": (
        (1769, 1771, ("bar_confederation_forces",)),
        (1794, 1794, ("kosciuszko_uprising_forces",)),
        (1830, 1831, ("november_uprising_polish_forces",)),
    ),
    "serbia": (
        (1167, 1216, ("serbian_grand_principality_nemanjic",)),
        (1218, 1345, ("kingdom_serbia_medieval",)),
        (1347, 1370, ("serbian_empire_medieval",)),
        (1403, 1458, ("serbian_despotate",)),
        (1805, 1814, ("serbian_revolutionary_forces_1804_1815",)),
        (1816, 1881, ("principality_serbia_1815",)),
    ),
    "greece": (
        (1821, 1829, ("greek_revolutionaries_1821",)),
        (1936, 1966, ("kingdom_greece_restored",)),
    ),
    "iran": ((1926, 1978, ("imperial_state_iran_pahlavi",)),),
}


WAVE7_CENTRAL_TRANSITION_YEAR_HOLDS: dict[str, frozenset[int]] = {
    "polish rebels": frozenset({1768, 1772, 1792, 1944}),
    "serbia": frozenset(
        {1166, 1217, 1346, 1371, 1402, 1459, 1804, 1815, 1882, 1995, 1999}
    ),
    "greece": frozenset({-480, 1935, 1967}),
    "iran": frozenset({1925, 1979}),
}


WAVE7_CENTRAL_FINAL_AUDIT_SIGNATURE = (
    "59293e0243abdbb36254452d7e15d7f454d51687183ab5f0b418b3a8179a57f6"
)
